### ISSUE TITLE
Add gitlab icon/link to footer social links

### ISSUE THREAD

**Issue by softinio** [xianmin/hugo-theme-jane#10]

**Comment by paskal** [comment]
If you could add [goodreads](https://www.goodreads.com/) icon (if there is such icon), it will be really nice. That's only social network I truly care about.
Also documentation could be updated, there are many icons in CSS but only few included in font - I've had to look into source files to understand what's available.

**Comment by xianmin** [comment]
@softinio @paskal  
I'm sorry.
For now, there is no better way to add icons. 
Next, I will fix this problem.

**Comment by xianmin** [comment]
Hi, @softinio @paskal , in recent commits, I update the new iconfont, and you could add `gitlab`, `goodreads` social links now.

**Comment by paskal** [comment]
Thanks a lot, looks great! Feel free to resolve this one.
