### ISSUE TITLE
Error while rendering "taxonomyTerm" in ...

### ISSUE THREAD

**Issue by WaygoneWilco** [xianmin/hugo-theme-jane#101]
I am automating a build on Google Cloud after pushing my repo to Github. It was working before, but now the build fails with this error:

`Building sites … ERROR 2018/08/01 18:08:45 Error while rendering "taxonomyTerm" in "": template: /workspace/themes/jane/layouts/_default/terms.html:11:5: executing "/workspace/themes/jane/layouts/_default/terms.html" at <partial "head.html" ...>: error calling partial: template: theme/partials/head.html:99:21: executing "theme/partials/head.html" at <.Site.IsServer>: can't evaluate field IsServer in type *hugolib.SiteInfo`

Not sure what is causing this.

**Comment by WaygoneWilco** [comment]
And not sure if this is a hugo error, or error with the Jane theme.

**Comment by Zebradil** [comment]
Which is Hugo version?

**Comment by WaygoneWilco** [comment]
Hugo Static Site Generator v0.46 linux/amd64 BuildDate: 2018-08-01T10:55:24Z

**Comment by shaform** [comment]
Perhaps you are not actually using v0.46? For example, see https://discourse.gohugo.io/t/solved-site-isserver-doesnt-work/13215.

**Comment by WaygoneWilco** [comment]
Ahh okay, maybe my hugo version on google cloud builder is out of date? I will check that, thank you.

**Comment by WaygoneWilco** [comment]
I'll go ahead and close this, issue on my end, thanks for guiding me to the solution.
