### ISSUE TITLE
Use Hugo pipes to process assets

### ISSUE THREAD

**Issue by maddovr** [xianmin/hugo-theme-jane#103]
Ever since Hugo 0.43, hugo in its extended variant has built-in support for assets pipelines, including SASS. Is it possible to drop webpack in favor of Hugo Pipes?

**Comment by xianmin** [comment]
I am not familiar with `Hugo-Pipes` now. 
And there is another Package we use:

https://github.com/xianmin/hugo-theme-jane/blob/a303b7c30c2c9ffbe81a861464973fd396b683ba/package.json#L31

I am not sure whether `Hugo-Pipes` support it.
I will take a look it, if I have time.

**Comment by maddovr** [comment]
Might I ask why using svgs as an iconfont instead of leaving them as is?

**Comment by xianmin** [comment]
@maddovr Just to reduce the number of requests.

**Comment by maddovr** [comment]
While it would indeed reduce the number of requests, said number isn't really significant due to the small amount of icons and the benefit of using sag instead of icon fonts are quite remarkable.
See (here)[https://css-tricks.com/icon-fonts-vs-svg/]

**Comment by shaform** [comment]
@maddovr It appears those svgs are actually converted into fonts? Therefore they are not inline svgs.

**Comment by maddovr** [comment]
@shaform exactly my point. I Think leaving them as svg makes much more sense
