### ISSUE TITLE
如何让文章中的图片显示在列表页上面？

### ISSUE THREAD

**Issue by cx4** [xianmin/hugo-theme-jane#105]
如题。使用more不管用。

**Comment by xianmin** [comment]
使用 `<!--more-->` 这个标签不管用吗？
把文章地址，以及文章 markdown 源文件的链接，发来看一下呢？

**Comment by cx4** [comment]
https://cx4.github.io/post/python2wx/

**Comment by shaform** [comment]
至少如果列表頁不是摘要，而是全文的話，就會顯示，摘要的情形倒是沒試過。

**Comment by cx4** [comment]
如果是全文的话就用不到more标签了。肯定是摘要。

**Comment by cx4** [comment]
`前言
最近看到网上有定时推送文章到微信的文章，其实这个小功能我一直在做，包括定时爬取内容用邮件发送等等。
不过网上都是python2.7的版本。对于使用python3的小白可能用起来比较困惑，手动改了一个`python3`的版本。</br>

![python2wechat](https://i.loli.net/2018/08/03/5b63dbfd294f5.png)

`
标签的位置，确定使用了。
