### ISSUE TITLE
手机上访问底部的上一篇下一篇怎么增加标题

### ISSUE THREAD

**Issue by starifly** [xianmin/hugo-theme-jane#106]
还有代码高亮主题颜色怎么改

**Comment by xianmin** [comment]
手机上访问底部的上一篇下一篇怎么增加标题？
答：这个需要修改源码，你可以查看这个文件：

https://github.com/xianmin/hugo-theme-jane/blob/1af02095e0f72916e1f4f54737215e36a6140c20/layouts/post/single.html#L66


代码高亮主题颜色怎么改？
答：可以使用 customCSS ，参考 hugo 文档：https://gohugo.io/content-management/syntax-highlighting/#generate-syntax-highlighter-css

**Comment by if2012** [comment]
@xianmin 
生成了syntax.css之后不生效，怎么回事？

**Comment by xianmin** [comment]
config 文件中有个这个配置：

```toml
customCSS = []            # if ['custom.css'], load '/static/css/custom.css' file
```

你有使用 `custom.css` 吗？然后将生成的 `syntax.css` 的内容复制到 `custom.css` 试试？

**Comment by if2012** [comment]
@xianmin 
使用了的，不生效。

**Comment by ifttl** [comment]
不生效的原因似乎是因为主题原本的语法高亮相关的 CSS 选择器是 `.post .post-content .highlight>` 开头的，比 hugo 生成的 syntax.css 里的选择器优先级高
