### ISSUE TITLE
TAG页面的链接

### ISSUE THREAD

**Issue by athurg** [xianmin/hugo-theme-jane#11]
目前TAG列表页面中，针对每个TAG生成的链接是类似
```html
<a href="/tags/TAG_NAME">
```

但实际上这个URL路径对应的是一个目录。建议修改为
```html
<a href="/tags/TAG_NAME/">
```

加一个路径分割的斜杠。

如果不加这个会有什么问题呢？以Nginx为例，当使用了端口转发时，如果Nginx监听的端口和用户访问的端口不一致，就会出现问题。

具体来说，Nginx在对URL对象是目录、且URL并不是斜杠结尾的时候，会直接返回301重定向。重定向的地址中，host是客户端访问的HOST，但是**端口就是Nginx监听的端口，而不是客户端访问的PORT**

比如说：Nginx监听在8081端口，外部采用端口转发将8082转发到Nginx的8081端口。

那么客户端访问

    http://test.com:8082/tag/myname

这个时候Nginx会返回301重定向，重定向的目的地是：

    http://test.com:8081/tag/myname/

访问就失败了。

这个当然Nginx也有一部分责任（301地址端口不正确），模板也应该有一部分责任（对路径的访问应该加上斜杠，而不是让web服务器去猜）。

当然管理员也可以调整一下nginx的配置解决这个问题。不过nginx的默认行为就是如此。建议这里修改一下，在路径上加上一个斜杠。

**Comment by jostyee** [comment]
直接提个PR吧，改动很小的

**Comment by xianmin** [comment]
感谢反馈！这的确是我没注意到的问题！ :+1:

**Comment by jostyee** [comment]
个人还是经常折腾博客程序的，说不定哪天又换了。

**Comment by xianmin** [comment]
@jostyee 理解 :smile:

**Comment by athurg** [comment]
我不介意，然而我已经在你的基础上改了。具体可见我的fork repo。虽然大部分代码没怎么动过，但是视觉上差异比较大。你如果不介意，可以加上去。 [Gooth](https://www.gooth.org)

**Comment by xianmin** [comment]
@athurg 哈哈！太好了！ :+1:
