### ISSUE TITLE
Add bilibili icon/link to footer social links

### ISSUE THREAD

**Issue by SenlinOS** [xianmin/hugo-theme-jane#110]
I have made the SVG icon: 
https://github.com/SenlinOS/databox/blob/master/bilibili.svg

**Comment by xianmin** [comment]
Thanks for the icon. Now bilibili icon is supported.

![deepinscreenshot_select-area_20180826143533](https://user-images.githubusercontent.com/2177570/44625476-58a35b00-a93d-11e8-9c44-0f380f02618f.png)

**Comment by SenlinOS** [comment]
I just wrote a HTML icon bar, manually replaced the code, it can be amended later @_@
***
Thank you for updating so quickly.
I looked at the effect and felt the icon was small.
So I enlarged the icons. (The size is still 128 x 128.)
https://github.com/SenlinOS/databox/blob/master/bilibili.svg

**Comment by xianmin** [comment]
OK! I updated.
By the way, it's easy to Increase icon font size use `custom.css`.

Maybe you could open another issue talk about E-mail suggestion.
