### ISSUE TITLE
Do not use pop-ups for emails.

### ISSUE THREAD

**Issue by SenlinOS** [xianmin/hugo-theme-jane#111]
Click on the email in the footer social links to pop up a new window.
I would like not to pop-up the window when clicking on e-mail.

**Comment by SenlinOS** [comment]
Re: lartpang
The email will pop up the mail client, but it will also pop up a browser window.
***
Do not look at my home page. I changed the HTML code by myself >o<
Fortunately, there are not many logs.

**Comment by lartpang** [comment]
“ it will also pop up a browser window.”？

Sorry, i didn't meet this problem... 
when i click my "mailto", it will call my meil client...
---

and, i would like to recommend a tool for you, it can encrypt your email address, but it doesn't affect your email.

http://tools.jb51.net/email/emailencode

**Comment by shaform** [comment]
I think this could be solved by removing `target="_blank"` for the mail link.

**Comment by SenlinOS** [comment]
> Sorry, i didn't meet this problem...
> when i click my "mailto", it will call my mail client...

Re: lartpang
Firefox will not pop up browser windows.
Chromium pops up browser window. 
(Linux OS)
