### ISSUE TITLE
界面的语言没有更新

### ISSUE THREAD

**Issue by adamweixuan** [xianmin/hugo-theme-jane#112]
1. 做了如下的设置，但是界面的语言仍是英文
```
defaultContentLanguage = "zh-cn"           # Default language to use
[Languages.zh-cn]
  languageCode = "zh-cn"
```
![image](https://user-images.githubusercontent.com/7525242/44834775-b1883180-ac64-11e8-86b6-f941ace7fc4c.png)
2. **请问有办法设置页面的宽度么**

**Comment by xianmin** [comment]
1. 目录栏的语言设置是更改：
https://github.com/xianmin/hugo-theme-jane/blob/91a6156ab9c3bcf6c48892d21508d326c725c38b/exampleSite/config.toml#L35

`name` 的值。

2. 目前修改页面的宽度需要自行改源码。后面我有时间的话，可以考虑添加这么一个设置。
