### ISSUE TITLE
有些 HUGO 主题可以通过点击作者直接列出他写的所有文章，JANE 有添加这个功能的想法吗？

### ISSUE THREAD

**Issue by endg** [xianmin/hugo-theme-jane#114]

**Comment by lartpang** [comment]
想法不错。

不过对于这个主题而言，感觉意义不大，毕竟已经有入口可以直接看到“文章归纳”了。

**Comment by endg** [comment]
有的，您可以看下这个ENGIMO主题，https://themes.gohugo.io/engimo/ ，而且他的一篇文章https://themes.gohugo.io/theme/engimo/docs/authors/ ，就是关于怎么添加作者及其链接作品的。

**Comment by shaform** [comment]
順便問問，一般會覺得有必要支援一篇文章有多個作者嗎

**Comment by shaform** [comment]
#147 merged 之後這個應該就可以 close 了？
