### ISSUE TITLE
In the homepage post summary, the latex is not rendering

### ISSUE THREAD

**Issue by vancities** [xianmin/hugo-theme-jane#118]
once you click readmore into the post, then it is rendering.

**Comment by xianmin** [comment]
You may add the `<!--more-->` summary divider where you want to split the article. 

https://gohugo.io/content-management/summaries/#user-defined-manual-summary-splitting


Related issues: 
- https://github.com/xianmin/hugo-theme-jane/issues/18
- https://github.com/xianmin/hugo-theme-jane/issues/105

**Comment by vancities** [comment]
The split is fine.
Just the equations are shown in the markdown style in "$$   $$" instead of "HTML" style in summary. 

Btw, is there a switch which could turn on the inline equation with "$ $" identifier?

**Comment by xianmin** [comment]
You could have a look at this issue: https://github.com/xianmin/hugo-theme-jane/issues/53 .

**Comment by xianmin** [comment]
This theme has been very different from the Evan theme.
I am not familiar with MathJax. And I found there are many configurations in MathJax's Docs. For additional configuration, I recommend using the `custom head` feature provided in this theme.
