### ISSUE TITLE
Pagination doesn't have default value

### ISSUE THREAD

**Issue by paskal** [xianmin/hugo-theme-jane#12]
Hello!

$subj:
```
Building sites … ERROR 2018/03/23 19:25:15 Error while rendering "taxonomy" in "": template: /srv/hugo/themes/hugo-theme-jane/layouts/_default/taxonomy.html:4:17: executing "content" at <.Paginate>: error calling Paginate: 'pager size' must be a positive integer
```
I think, `paginate` could have some default if it's not defined in site configuration, as well as `params.archive-paginate`. Examples of same thing done: https://github.com/cboettig/hugo-now-ui/issues/9, https://github.com/yursan9/manis-hugo-theme/issues/4 (you might want to add defaults somewhere else as well).

By the way, your theme is *amazing*. If there is *any* way I could help you, please tell me.

**Comment by xianmin** [comment]
Thank you for the report and Information provided!
I will fix it. :smile:

**Comment by paskal** [comment]
I've checked it, paginate already [have default of 10](https://gohugo.io/templates/pagination/#configure-pagination), I'll prepare PR to set archive-paginate to same value by default.

**Comment by xianmin** [comment]
@paskal Thanks for your pull requests.

**Comment by paskal** [comment]
I'm not sure github sent notifications to mentioned authors, so posting double there: theme highlight is out, this very theme is in it, additional info on https://github.com/paskal/terrty/issues/1.
Also I've made choice, and I'll use this theme from now on. Thanks again for your work!

**Comment by xianmin** [comment]
It sent notifications to me when you mentioned me.
I am so honored that you like this theme. :smile: 

Would you mind if I put your blog link in the `README.md` `who use hugo-theme-jane` section?  And If could, give me a short Introduce.

**Comment by paskal** [comment]
```
[Notes on Blue Skies](https://terrty.net) - Personal blog in Russian by @paskal
```
Other blog in this list (the one with thousand posts) is really nice, thanks for sharing these.
