### ISSUE TITLE
请问一些，这里面的html ，是使用了什么HTML模板？

### ISSUE THREAD

**Issue by MrBenWang** [xianmin/hugo-theme-jane#127]
比如：https://github.com/xianmin/hugo-theme-jane/blob/master/layouts/_default/section.html

我前端会一些，也仅限于html，js，css这些基本。想修改这个不知道如何下手，使用了什么模板语言？麻烦告知一下。

**Comment by xianmin** [comment]
你可以看一下 hugo 的官方文档： https://gohugo.io/templates/introduction/
