### ISSUE TITLE
我制作了[爱发电]网站的页脚链接图标

### ISSUE THREAD

**Issue by SenlinOS** [xianmin/hugo-theme-jane#130]
https://github.com/SenlinOS/databox/blob/master/afdian.svg
[爱发电]网站 **https://afdian.net** 是国内刚刚起步的类似 Patreon 的赞助网站。
如果感觉适合就添加页脚社交链接图标吧～
如果感觉不适合，那就不用添加～ 
（我自己写了个HTML的代码，已经自行添加了）

**Comment by xianmin** [comment]
这个太小众了，暂时还是不添加吧……
