### ISSUE TITLE
Markdown语法高亮有办法改吗？感觉现在的不太好看

### ISSUE THREAD

**Issue by Praying** [xianmin/hugo-theme-jane#133]
![image](https://user-images.githubusercontent.com/9401557/47283339-965af200-d615-11e8-8a26-1dabdd4f1a77.png)

**Comment by shaform** [comment]
You'll have to turn on syntax highlight https://github.com/xianmin/hugo-theme-jane/blob/master/exampleSite/full-config.toml#L15

**Comment by Praying** [comment]
thanks very much @shaform
