### ISSUE TITLE
A space before the first line of R code trunk

### ISSUE THREAD

**Issue by larryleihua** [xianmin/hugo-theme-jane#137]
There is always a space before the first line of an R trunk:

For example, if I use the following, then there will be a space displayed before x, which is kinda annoying to my eyes.

```{r}
x <- 1+1
```

Btw, thank you for making this beautiful theme!

**Comment by xianmin** [comment]
Maybe you havn't enable the `Highlight options` ?

https://github.com/xianmin/hugo-theme-jane/blob/335d0c2f69149f63a0a7db0252a0628ac5a0c4a1/exampleSite/full-config.toml#L15-L20

Related issue: https://github.com/xianmin/hugo-theme-jane/issues/46

**Comment by larryleihua** [comment]
Highlight was on, and it seems that Blogdown which I used to create the hugo webiste does not support codes highlighting well. With Blogdown, we can create web pages using R markdown so that R codes can be run on the fly. However, with R markdown (instead of ordinary markdown), codes highlighting does not work well.

**Comment by larryleihua** [comment]
I think I have just solved the problem by following the first 2 steps from the following link to use highlight.pack.js for codes highlighting:

https://amber.rbind.io/blog/2017/11/15/syntax-highlighting/

**Comment by xianmin** [comment]
I am glad to hear that you solved this problem! :smile:
