### ISSUE TITLE
时间格式的样式问题

### ISSUE THREAD

**Issue by MrBenWang** [xianmin/hugo-theme-jane#140]
有两个地方的只要是 “2018-10-13 14:25:30” 这种格式，总会换行
点击【归档】
![点击【归档】](https://user-images.githubusercontent.com/9692054/48111123-f34bde80-e28a-11e8-9346-45db9c09a4b7.jpg)

点击【分类】-【查看更多】
![点击【分类】-【查看更多】](https://user-images.githubusercontent.com/9692054/48111122-f2b34800-e28a-11e8-8f44-b54ac3ac662c.jpg)

**Comment by xianmin** [comment]
1. 时间的样式问题，可以用 `custom.css` 自行修改宽度。

2. 分类页我计划重新设计。

**Comment by MrBenWang** [comment]
我个人认为这两个地方，是不需要 小时分钟的。 

小时分钟的时间格式，应该只出现在首页，或者 文章的内容中。

**Comment by xianmin** [comment]
在配置中有一个 `dateFormatToUse` 选项，可以修改这个选项改变时间格式。

**Comment by MrBenWang** [comment]
配置中的  dateFormatToUse 是一个全局的参数，但是我期望 在不同的地方显示的时间不同：

```
我的配置  dateFormatToUse = "2006-01-02 15:04"
```
1、在【首页-文章列表】和 【文章正文】中，显示的 完整的 日期和时间；
2、在【归档】和【分类】等，只显示日期，不显示时间。  否则就出现 1楼 图中的换行
