### ISSUE TITLE
文件的编码格式问题

### ISSUE THREAD

**Issue by MrBenWang** [xianmin/hugo-theme-jane#141]
\jane\layouts\_default\taxonomy.html   文件编码为 `ISO-8859-1`，导致 使用 windows 记事本，编辑后。页面无法显示。

同时，请留意下，这些文件的编码格式
```
{'encoding': 'Windows-1252', 'confidence': 0.73, 'language': ''}        \jane\assets\sass\_partial\_header\_menu.scss
{'encoding': 'Windows-1254', 'confidence': 0.5241492539421478, 'language': 'Turkish'}   \jane\CHANGELOG.md
{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}  \jane\exampleSite\content\post\image-preview.md
{'encoding': None, 'confidence': 0.0, 'language': None} \jane\layouts\partials\custom_head.html
{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}  \jane\layouts\_default\taxonomy.html
{'encoding': 'Windows-1254', 'confidence': 0.5171999658650784, 'language': 'Turkish'}   \jane\README.md
{'encoding': 'Windows-1252', 'confidence': 0.6994171220400728, 'language': ''}  \jane\static\favicon.ico
```

**Comment by xianmin** [comment]
你重新 `git clone` 一下呢？在我的开发环境下所有文件都是 `UTF-8` 编码。

**Comment by MrBenWang** [comment]
你可以用我的，python脚本运行看一下 

https://github.com/MrBenWang/MyBackUp/blob/master/python/006-show_file_encoding.py

**Comment by xianmin** [comment]
不好意思，linux 的 `file` 命令查看文件编码有时候会不太准确。

知识有限，我不确定这个问题是否重要……

我查看了另外两个 github 上的开源项目，也存在有个别文件的编码是 `ISO-8859-1` 、 `Windows-1254` 和 `Windows-1252` 。这也许是不同开发者使用的不同的编码环境导致的。

**Comment by MrBenWang** [comment]
我认为不会影响开发，但是可能会出现莫名其妙的问题。

因为不同的编辑器，所支持的编码格式会不同。
比如我的win10电脑上 【 windows 记事本】，只有四种 编码格式。 里面就没有 ISO-8859-1。
导致我用 记事本 修改【\jane\layouts\_default\taxonomy.html】后，页面打不开。找了很久的原因，才发现是这个问题。

修改或者不修改，看个人把。
