### ISSUE TITLE
Failed to find a valid digest in the 'integrity' attribute for resource. Github will compress the file

### ISSUE THREAD

**Issue by MrBenWang** [xianmin/hugo-theme-jane#143]
我今天下午获取的最新 theme，并且同步到了github，发现浏览器报错。
在本地测试的时候，没有问题。
我在网上找到[使用SRI保护你的网站免受第三方CDN恶意攻击](https://segmentfault.com/a/1190000011337230)，是不是没有更新 hashcode呢？

Failed to find a valid digest in the 'integrity' attribute for resource 'https://mrbenwang.github.io/js/main.dee43230127a73d039a734510fa896c89c3c7ce0cf0be0c7a7433f8fd69b76dc.js' with computed SHA-256 integrity 'Y4JR9CMGMPAzXYxnSOU6lvlLcmcJILYMCaVv3Ivs4hQ='. The resource has been blocked.

**Comment by xianmin** [comment]
查看一下 `public/js` 文件夹下的 JS 文件，如果是 `main.638251f4230630f0335d8c6748e53a96f94b72670920b60c09a56fdc8bece214` 就是没问题的。

我的站点 https://www.xianmin.org/ 没这个问题。方便的话提供一下 Hugo 的版本。

**Comment by MrBenWang** [comment]
Hugo Static Site Generator v0.49 windows/amd64 BuildDate: 2018-09-24T10:01:53Z

生成的是 js 文件名是 main.dee43230127a73d039a734510fa896c89c3c7ce0cf0be0c7a7433f8fd69b76dc.js	
https://github.com/MrBenWang/mrbenwang.github.io/tree/master/js

我很是奇怪，dee43230127a73d039a734510fa896c89c3c7ce0cf0be0c7a7433f8fd69b76dc  这个字符串，只会出现 hugo生成的 public 里面。

**Comment by xianmin** [comment]
你升级到最新的 hugo 版本再试一试呢？

**Comment by xianmin** [comment]
在 `Hugo theme` 站点生成的 `Demo` 页面没有这个问题： 
https://themes.gohugo.io/theme/hugo-theme-jane/

你可以检查一下是否是修改了 html 文件的原因。

另外，你可以将主题中的你需要修改的 `layouts/*.html` ，复制到你站点根目录下的 `layouts/*.html` （注意文件名和路劲要相同），然后再进行修改。这样就不必改 Jane 主题的源码了。

如果依然出现错误，可以安装 `Hugo_extended` 版本试试，它会重新编译相关代码。

**Comment by MrBenWang** [comment]
我好像找到原因了，是因为 文件的大小不一致，但是 同步在本地的时候，大小就又一致了。很是奇怪，好像github 做了特殊处理的一样。我尝试过，都没有发现什么不妥：
1、重新上传，再下载。
2、对比过文件格式，
3、从github 拉到本地。

https://github.com/ijunjie/ijunjie.github.io/blob/master/js/main.dee43230127a73d039a734510fa896c89c3c7ce0cf0be0c7a7433f8fd69b76dc.js  大小 ：229 lines (199 sloc)  **5.96 KB**

https://github.com/MrBenWang/mrbenwang.github.io/blob/master/js/main.dee43230127a73d039a734510fa896c89c3c7ce0cf0be0c7a7433f8fd69b76dc.js 大小：229 lines (199 sloc)  **5.74 KB**

**Comment by zzhDmon** [comment]
@MrBenWang 这个最后是如何解决的呢，我也碰到有相同的问题

**Comment by MrBenWang** [comment]
> @MrBenWang 这个最后是如何解决的呢，我也碰到有相同的问题

我是把 main.js 里面所有的代码，拷贝到  自定义的js里面。  可以参考 https://github.com/MrBenWang/mrbenwang.github.io/blob/master/js/custom.js

**Comment by shaform** [comment]
看起來兩個檔案的差別在於換行格式一個是 `UNIX` 一個是 `DOS`.

參考 https://www.jianshu.com/p/8d33019d1c69

**Comment by MrBenWang** [comment]
我在Public 文件夹下面新建一个文件，名为： `.gitattributes`
内容是，只有一行：
`*.js -text`

原因就是 @shaform 所说的，操作系统间的换行符：CRLF, LF 导致的。这个心病终于解决了，谢谢shaform  和 xianmin

**Comment by spilledyear** [comment]
我也遇到了这个问题，最后我找到themes\jane\layouts\partials\scripts.html 文件 ，找到对应的那行代码

**Comment by tpkeeper** [comment]
> 我在Public 文件夹下面新建一个文件，名为： `.gitattributes`
> 内容是，只有一行：
> `*.js -text`
> 
> 原因就是 @shaform 所说的，操作系统间的换行符：CRLF, LF 导致的。这个心病终于解决了，谢谢shaform 和 xianmin

解决了
