### ISSUE TITLE
Chore: busuanzi 404

### ISSUE THREAD

**Issue by yangwenmai** [xianmin/hugo-theme-jane#146]
这个资源 URL 404：`https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js`

**Comment by shaform** [comment]
> 因七牛强制过期『dn-lbstatics.qbox.me』域名，与客服沟通无果，只能更换域名到『busuanzi.ibruce.info』！

https://busuanzi.ibruce.info/

**Comment by xianmin** [comment]
I think we have fixed this: https://github.com/xianmin/hugo-theme-jane/pull/129
