### ISSUE TITLE
shortcode-notice can't contain common symbols

### ISSUE THREAD

**Issue by MrBenWang** [xianmin/hugo-theme-jane#153]
shortcode-notice： 不能包含常用符号，比如 单引号`'`，斜杠`/`，问号`?`，等等

{{% notice Info test's test %}}
test
{{% /notice %}}

`
C:\test\mrbenwang.github.io-hugo>hugo server    

Building sites … Total in 95 ms     

Error: Error building site: "C:\test\mrbenwang.github.io-hugo\content\post\0021-logical-fallacy-list-1.md:69:28": unrecognized character in shortcode action: U+0027 '`'`'. Note: Parameters with non-alphanumeric args must be quoted
`

**Comment by MrBenWang** [comment]
{{% notice info Test Title %}}
{{% /notice %}}

这时候，title 会是 `info`，不是`Test Title`。

{{% notice info TestTitle %}}
{{% /notice %}}

这时候，title 才会是 `TestTitle`。

**Comment by shaform** [comment]
`Parameters with non-alphanumeric args must be quoted`

so you could use

```
{{% notice "Info test's test" %}}
test
{{% /notice %}}
```

**Comment by MrBenWang** [comment]
> `Parameters with non-alphanumeric args must be quoted`
> 
> so you could use
> 
> ```
> {{% notice "Info test's test" %}}
> test
> {{% /notice %}}
> ```

thx
