### ISSUE TITLE
Error building site:

### ISSUE THREAD

**Issue by icf20** [xianmin/hugo-theme-jane#158]
`Error: Error building site: failed to render pages: render of "page" failed: execute of template failed: template: _default/single.html:11:5: executing "_default/single.html" at <partial "head.html" ...>: error calling partial: "..../themes/jane/layouts/partials/head.html:28:16": execute of template failed: template: partials/head.html:28:16: executing "partials/head.html" at <index ($.Site.Data.a...>: error calling index: value has type []string; should be string
`
i dont exactly understand why i got this error....

**Comment by shaform** [comment]
It seems that you have specify multiple authors for your site or article or you have used a list format for specifying the author for an article, which is not supported. See #147.

**Comment by shaform** [comment]
Guest posts are supported if the post has only 1 author (which could be different from other posts). Multiple author support might be added in the future if there is demand, but currently it's not supported.
