### ISSUE TITLE
baidu_analytics 配置项不起作用

### ISSUE THREAD

**Issue by zero4drift** [xianmin/hugo-theme-jane#166]
在 config.toml 添加 baidu_analytics 配置项，使用 hugo 建立博客时并没有给 html 文件加上百度分析的 header 部分；

配置文件中另外两个关于百度的配置项 baidu_push 和 baidu_verification，项目内全局搜索了一下，这两个应该跟配置 baidu_analytics 没什么关系。

这是个 bug 吗？还是我使用不当？

**Comment by xianmin** [comment]
![deepinscreenshot_select-area_20190120201316](https://user-images.githubusercontent.com/2177570/51439064-ee29f780-1cef-11e9-97bc-8a9772f6c49e.png)


请问你的 baidu_analytics 配置项的内容，是使用的类似于上图红框中的一串字符串吗？

请在浏览器中，右键检查一下网页源码，在 <body> 标签的底部是否有 baidu_analytics 相关的代码生成？

**Comment by xianmin** [comment]
![deepinscreenshot_select-area_20190121214209](https://user-images.githubusercontent.com/2177570/51478104-73cba700-1dc5-11e9-9b1a-4644e3bbc517.png)

我配置  `baidu_analytics = "test"` ，在 Demo 站点中是可以生成相关代码的。奇怪……
