### ISSUE TITLE
关于目录的问题。

### ISSUE THREAD

**Issue by hzl-666** [xianmin/hugo-theme-jane#171]
我目录功能已经开启，本地测试的时候都有效，但是上传后文章就是不会出现目录按钮。
toc状态；toc = true。

**Comment by hzl-666** [comment]
文章开头没有修改toc的状态。

**Comment by xianmin** [comment]
请问你站点的地址是？
当你打开 [DEMO](http://en.xianmin.org/hugo-theme-jane/) 站点的时候，会显示目录吗？

**Comment by hzl-666** [comment]
DEMO会显示，我已经解决了，是github的原因，导致一个js没起来，，在issue中找到了这个问题解决办法。

**Comment by tenkasky** [comment]
請問zhl-666 這問題你是如何解決？我也遇到相同問題

**Comment by WooHooDai** [comment]
我也遇到了相同的问题。在本地通过hugo server预览文章有目录，但是上传到GitHub以后，就没有
请问是在哪个issue中找到了解决方法？ @hzl-666
