### ISSUE TITLE
文章页面后缀支持自定义配置

### ISSUE THREAD

**Issue by HJDev** [xianmin/hugo-theme-jane#172]
现在使用hugo的配置：

defaultExtension = "html"
defaultLayout = "post"

但无法显示后缀为HTML，仍然以/为结尾，希望可以支持下，谢谢。

**Comment by xianmin** [comment]
你试试使用 `uglyurls = true` ？

参考： https://gohugo.io/content-management/urls/#ugly-urls

**Comment by HJDev** [comment]
谢谢
