### ISSUE TITLE
希望大神可以同时渲染下其他目录的博文，谢谢。

### ISSUE THREAD

**Issue by HJDev** [xianmin/hugo-theme-jane#173]
@xianmin  希望可以同时渲染下其他的目录的博文，这样可以把不同类别的博文分文件夹存放，有利于对博文的归类。谢谢大神提供这么好的主题

我的博文目录：

content/
├── Xday.zip
├── html
├── post
└── times

**Comment by xianmin** [comment]
关于文件夹分类的问题，你可以试试在 `post/` 目录下创建多个 **子目录** 来进行分类？

**Comment by HJDev** [comment]
这样是可以渲染，但后缀就变成了 `/post/html/xxxxxxxxx.html`，不知道能不能把 `/post` 去掉。谢谢

**Comment by xianmin** [comment]
不好意思， `post/` 文件夹是写死了的，不好改，因为 **归档** 、 **标签** 、 **分类** 页面都是基于 `post/` 文件夹下的文件生成的，这是这个主题的限制。
