### ISSUE TITLE
How to remove docs from menu

### ISSUE THREAD

**Issue by vivekkrkarn** [xianmin/hugo-theme-jane#174]
How to remove docs from menu. no option provided in confing.toml. also cant remove it by editing theme partials.
![screenshot_2019-02-11 jane - a super concise theme for hugo](https://user-images.githubusercontent.com/22608849/52552030-cb799300-2e04-11e9-9223-cf5618cf80d7.png)

**Comment by vivekkrkarn** [comment]
got the solution.

**Comment by longed** [comment]
How did you solve this? Please share us your solution. Thanks.

**Comment by longed** [comment]
After some attempts, I found one solution.
Just remove posts (in the `content/post` directory) under the 'docs' then 'docs' will disappear.
