### ISSUE TITLE
How to use series

### ISSUE THREAD

**Issue by Splaxi** [xianmin/hugo-theme-jane#177]
Hi,

I started to use your theme for my blog, but I can't seem to understand how to get starting using the series Taxonomy.

I tried reading the #62 issue, but it is a bit unclear how to start using the series.

If I create the series inside my Front Matter for the specific page, the build fails with:
```
Building sites … ERROR 2019/02/25 15:36:57 Error while rendering "page" in "post\\": template: post\single.html:11:5: executing "post\\single.html" at <partial "head.html" ...>: error calling partial: template: _internal/opengraph.html:32:17: executing "_internal/opengraph.html" at <index $siteSeries $n...>: error calling index: index of untyped nil
```

Any help or pointers would very helpful!

**Comment by xianmin** [comment]
Hi @Splaxi , Have you solved this problem?

If you want use `series` taxonomy, you should add some options in your `site config` : 

```
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
```

You can also see here: [Hugo Taxonomy Defaults 
](https://gohugo.io/content-management/taxonomies/#default-taxonomies)

**Comment by Splaxi** [comment]
Hi @xianmin ,

I did not solve my issue, so thank you very much for getting back. I'll give it a look later today and see if I can get things to work.

I tried reading the mentioned link, but either I was to tired or simply overloaded with to much infomation at that time.

**Comment by Splaxi** [comment]
Okay - now the build doesn't fail anymore, so thank you!

I learned that the `{{< series value >}}` has to be lowercased. Maybe we could note that somewhere. Now things work like expected!

**Comment by xianmin** [comment]
@Splaxi You are welcome! Glad to hear this good news.
You are right. The documentation for this project is too scarce.
But I am a little busy recently, I am sorry that the reply is late.

**Comment by Splaxi** [comment]
Let me help you out!

Would you like to have your documentation in wiki or small / simple markdown files inside the repo? 

Having them part of the repo would enable the users to have it part of their download.

**Comment by xianmin** [comment]
@Splaxi Great! 
I thought about this. Maybe simple markdown files inside the repo is better. This repo already has some examples in the `exampleSite/` folder. Real file examples easy to help users understand. Like this: 

Shortcodes preview: https://github.com/xianmin/hugo-theme-jane/blob/master/exampleSite/content/post/shortcodes-preview.md

What do you think?

**Comment by Splaxi** [comment]
Like in we create posts that lives in the example site, so people actually browse it from the local site? 😀

**Comment by xianmin** [comment]
@Splaxi Yes. And they can also see it in the [Jane Demo Site - A simple theme for Hugo](https://www.xianmin.org/hugo-theme-jane/)

**Comment by Splaxi** [comment]
Deal!
