### ISSUE TITLE
change body font(or title font)

### ISSUE THREAD

**Issue by Victorfy** [xianmin/hugo-theme-jane#178]
if I want to change body font to KaiTi, what should I do?
BTW, what about title font(about the website on the left-top)

thx!

**Comment by xianmin** [comment]
You could use `Custom Css` . For example: https://github.com/xianmin/hugo-theme-jane/issues/7

**Comment by Victorfy** [comment]
I tried to do that, but it seems not working.
Can you give a example to change blog body.
thx a lot!
