### ISSUE TITLE
How to enable utterance?

### ISSUE THREAD

**Issue by jinfagang** [xianmin/hugo-theme-jane#179]
Seems already support utterance, how to enable it and configging it? Any tutorials?

**Comment by jintian93** [comment]
How to using github comment in About page. I can have in article but not on about page.

**Comment by xianmin** [comment]
@jinfagang  You'd better see the [utterances](https://utteranc.es/) document first. Then add the options blew: 

https://github.com/xianmin/hugo-theme-jane/blob/eef5059d961cfef14e0d58c3e23a4400a6a0a516/exampleSite/full-config.toml#L134-L137

**Comment by xianmin** [comment]
@jintian93 Check your `about.md` file, there is a line in the `Front Matter` : 

```
comment: false
```

Just delete this line.

**Comment by jinfagang** [comment]
@xianmin That works, thank you. BTW, how to disable the link button when using a external link?

![image](https://user-images.githubusercontent.com/21303438/53861791-22e3db00-4020-11e9-81ec-8a7b61d5651f.png)

How to remove it?

If I want click the link and jump a pdf file in my blog, what shoud I do and where should I place my pdf file? Many thanks!

**Comment by xianmin** [comment]
@jinfagang 
The easy way, you could add a `Custom CSS` : 
``` css
.menu-item-link .iconfont {
  display: none;
}
```

About the pdf file, you can put it to the `static/` folder in your site root folder. The url path is `/example.pdf` .
