### ISSUE TITLE
Layout of post summary incorrect

### ISSUE THREAD

**Issue by j620656786206** [xianmin/hugo-theme-jane#18]
I don't know why my Chinese post show like this

https://github.com/j620656786206/hugoblog/blob/master/static/img/postscreenshot.jpg

Does anyone can help me? Thanks!

**Comment by xianmin** [comment]
You may add the  summary divider where you want to split the article. 

https://gohugo.io/content-management/summaries/#user-defined-manual-summary-splitting

**Comment by j620656786206** [comment]
I see, thank you!
