### ISSUE TITLE
布署到阿里云OSS上所有的链接都跳回了主页

### ISSUE THREAD

**Issue by pandahereboy** [xianmin/hugo-theme-jane#185]
你好，我使用`jane` 做为theme并布署到阿里云上时，遇到一个问题与 hexo 的问题类似（可参见如下链接:https://yq.aliyun.com/articles/653541)

因为OSS / AWS S3 要求是全路径的，而`jane`我找不到有哪个配置是可以实现类似`/post/test/index.html` 而不是`/post/test/`.

你可以告诉我怎么做吗？

**Comment by shaform** [comment]
Try ugly URLs https://gohugo.io/content-management/urls/#ugly-urls

**Comment by pandahereboy** [comment]
> Try ugly URLs https://gohugo.io/content-management/urls/#ugly-urls

谢谢，这个参数我试过了。仅可以解决 `/post`下生成的文章链接问题，甚至我们可以在 `hugo new post/xxx.md` 里直接指定: `url: xxx/xxx/xxx.html` 然后再生成静态页面。但仍然是只解决post列表的文章链接问题，对于 `归档` , `分类` ，`标签`等需要聚合的操作还是没办法解决。

**Comment by pandahereboy** [comment]
或者单页应用的theme...

**Comment by shaform** [comment]
I've did some tests, setting `uglyurls = true` does move `/tags/` to `/tags.html` and `/tags/footnote/` to `/tags/footnote.html`.

One thing to notice is that the URLs on the menu is hardcoded in config.toml `[[menu]]` so if you want to change the URLs in menu, you'll also need to change it.

**Comment by pandahereboy** [comment]
it worked, thanks.
