### ISSUE TITLE
execute of template failed: rss.xml

### ISSUE THREAD

**Issue by yahgr** [xianmin/hugo-theme-jane#188]
I followed your setup instructions for the example site, but the "hugo server" command fails: 
> Error: Error building site: failed to render pages: render of "Jane - A super concise theme for Hugo" failed: "/home/test/page/themes/jane/layouts/rss.xml:2:19": execute of template failed: template: rss.xml:2:19: executing "rss.xml" at <.Site.Config.Service...>: can't evaluate field RSS in type services.Config

Test with Hugo Static Site Generator v0.54.0/extended linux/386 BuildDate: 2019-02-01T18:13:18Z

**Comment by shaform** [comment]
I think this might be caused by https://github.com/xianmin/hugo-theme-jane/pull/184.
Can you try upgrading your Hugo and see if the problem persists?

I don't have the error you mentioned with the following version

> Hugo Static Site Generator v0.55.4/extended linux/amd64 BuildDate: 2019-04-25T10:11:27Z

**Comment by user1121114685** [comment]
是的，升级到最新5.55，就没有问题了

Hugo Static Site Generator v0.55.5-A83256B9 windows/amd64 BuildDate: 2019-05-02T13:04:07Z

**Comment by yahgr** [comment]
I upgraded to hugo_0.55.4_Linux-32bit.deb, now it works.
Thx
