### ISSUE TITLE
Error executing 'hugo'

### ISSUE THREAD

**Issue by Deckon** [xianmin/hugo-theme-jane#19]
Greetings.
when I execute the command 'hugo' to build the static site I get this error

`Building sites … ERROR 2018/03/30 10:07:51 Error while rendering "taxonomyTerm" in "": template: /home/deckon/Documentos/Hugo/blog/themes/jane/layouts/_default/terms.html:42:19: executing "content" at <len $.Site.Taxonomie...>: error calling len: len of untyped nil`

**Comment by xianmin** [comment]
I'm not sure where the problem is.

Maybe this will help you:  https://discourse.gohugo.io/t/len-of-untyped-nil/7484/4

**Comment by Deckon** [comment]
It was my mistake, I added an extra language line for testing and forget to delete it at the end.
Thanks

**Comment by xianmin** [comment]
You are welcome, it's my pleasure. :smile:
