### ISSUE TITLE
请问一下, 为什么我的代码块是这样的?

### ISSUE THREAD

**Issue by toure00** [xianmin/hugo-theme-jane#193]
是我什么地方没设置好吗
![image](https://user-images.githubusercontent.com/33457469/57983202-b3f41b00-7a81-11e9-93b6-831d9408b4aa.png)

**Comment by toure00** [comment]
我的markdown是这样的 , 应该没有问题吧
![image](https://user-images.githubusercontent.com/33457469/57983293-a5f2ca00-7a82-11e9-8437-a8a3068a29c9.png)

**Comment by xianmin** [comment]
你设置代码高亮了吗？有一个 `full-config.toml` 文件，你可以参考一下：

https://github.com/xianmin/hugo-theme-jane/blob/ac8907b4f56990336daf0c6851bf3b28fc5fde2b/exampleSite/full-config.toml#L15-L20

如果还是不行，麻烦提供一个预览地址。

**Comment by toure00** [comment]
谢谢啊 可以了
