### ISSUE TITLE
how to disable automatic fraction rendering?

### ISSUE THREAD

**Issue by hellt** [xianmin/hugo-theme-jane#194]
Hello, if I type an IP address in a plain text mode like 10.10.10.1/32, it renders out as a fraction for the last octet.

How do I disable this?

example - ![image](https://user-images.githubusercontent.com/5679861/57915342-3ff71e80-7899-11e9-862c-f14054c0fe2f.png)

**Comment by Zebradil** [comment]
I think you need to disable `smartypants` option. More info here: https://gohugo.io/content-management/formats/#blackfriday-options

**Comment by hellt** [comment]
thanks @Zebradil! that was it

I added to `config.toml`
```
  [blackfriday]
    fractions = false
```
to resolve this issue.
