### ISSUE TITLE
Add line break in yaml title

### ISSUE THREAD

**Issue by c1au6i0** [xianmin/hugo-theme-jane#195]
I would like to break the title in 2 lines. I tried the syntax indicated [here](https://discourse.gohugo.io/t/solved-add-line-break-in-yaml-file/13446), and to use the pipe `|` without  success. Any hint?
Thanks
Claudio

**Comment by xianmin** [comment]
Like this?

![DeepinScreenshot_select-area_20190606110133](https://user-images.githubusercontent.com/2177570/59003960-975e2e00-884a-11e9-9894-c46e48993d66.png)

```
  logoTitle = "Jane<br>aaa" 
```

But you need to change the title style by using `custom.css`

**Comment by c1au6i0** [comment]
Hi Xianmin, thank you for your reply.
I meant the title of the `RMarkdown` post. Sorry for the confusion!
