### ISSUE TITLE
文章转发到朋友圈没有logo图标

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#202]
文章转发到微信，没有logo图标
不知道如何能支持显示图标

**Comment by xianmin** [comment]
感谢反馈！

这个是微信分享机制的问题。网上找了一下，目前没有好的办法。

**Comment by luckrill** [comment]
谢谢你，
是我把文章分享到微信，不能显示 logo图片。 
就随口问问你的。

当初使用 jane，出现的 .URL WARN message <https://github.com/xianmin/hugo-theme-jane/commit/18433ddbbd2cb6442926f822cb5df349680c7fcb> 
我也是软件工程师，但界面部分非常不熟悉
自己尝试修改，地方比较多，判断不出修改哪个位置合适，之后就修改出错了。
看到你提交修复，非常开心。 感谢你

之后再次阅读你的博客文章，颇有感觉，也购买了 刻意练习
还没有时间看书

这两天刚刚发布了一个 markdown 工具，你也可以试试 http://markdown.readmorejoy.com/ <http://markdown.readmorejoy.com/>



蒋志祥
邮箱：luckrill@163.com <mailto:luckrill@163.com>
微信／电话：13520242339
网站 https://www.readmorejoy.com <https://www.readmorejoy.com/>
论坛 https://topic.readmorejoy.com <https://topic.readmorejoy.com/>

**Comment by xianmin** [comment]
日常维护而已，不必客气。
谢谢你推荐的工具，看上去很不错，哈哈！ :smile:
