### ISSUE TITLE
How to set the text number of article which show at home page ? 

### ISSUE THREAD

**Issue by Gan-Jason** [xianmin/hugo-theme-jane#205]

**Comment by xianmin** [comment]
Sorry, I didn't understand what you mean.

**Comment by Gan-Jason** [comment]
I mean that how to set the number of each articles' word which show at home page .

**Comment by Gan-Jason** [comment]
> Sorry, I didn't understand what you mean.
I mean that how to set the number of each articles' word which show at home page .

**Comment by Gan-Jason** [comment]
> Sorry, I didn't understand what you mean.

I mean that how to set the number of each articles' word which show at home page .

**Comment by Gan-Jason** [comment]
And why my categories don't show anything even thought i've configure it at config.toml and each article

**Comment by Gan-Jason** [comment]
And why my categories don't show anything even thought i've configure it at config.toml and each article.
![image](https://user-images.githubusercontent.com/48959194/60771320-f4365800-a118-11e9-84be-197e77791d3f.png)

**Comment by shaform** [comment]
Use `summaryLength`: https://gohugo.io/content-management/summaries/#automatic-summary-splitting

**Comment by Gan-Jason** [comment]
> Use `summaryLength`: https://gohugo.io/content-management/summaries/#automatic-summary-splitting

thx so much
