### ISSUE TITLE
支持Valine评论吗

### ISSUE THREAD

**Issue by pzb568** [xianmin/hugo-theme-jane#207]

**Comment by xianmin** [comment]
Not yet. Welcome to PR! :smile:

**Comment by Bennett-Yang** [comment]
> Not yet. Welcome to PR!

I pulled request to meet this demand. Would you please check it?

**Comment by xianmin** [comment]
Thanks @Bennett-Yang ! This theme support Valine now. https://github.com/xianmin/hugo-theme-jane/pull/235
