### ISSUE TITLE
Allow lastmod date to be updated according to git info while not displaying the commit hash.

### ISSUE THREAD

**Issue by shaform** [xianmin/hugo-theme-jane#209]
1. In #206, a commit hash is appended to the lastmod date when `enableGitInfo = true`.
2. When `enableGitInfo` is set as `false` the lastmod date would not be updated according to git info.
3. It might be nice to allow the lastmod date to be updated according to git message while not showing the commit hash. (Originally, this was possible by setting `enableGitInfo = true` if #206 was not merged.)

**Comment by xianmin** [comment]
Good suggestion!
Your PR https://github.com/xianmin/hugo-theme-jane/pull/210 has been merged.
Thank you! :smile:
