### ISSUE TITLE
双语支持有bug吗？

### ISSUE THREAD

**Issue by lengyueyang** [xianmin/hugo-theme-jane#215]
在配置里面如下设置：

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "zh-cn"           # Default language to use

[langusges]
[languages.en]
  title = "DR Medical"
  languageName = "English"
  contentDir = "content/en"
  weight = 2

[languages.zh-cn]
  title = "深度识医"
  languageName = "中文"
  contentDir = "content/zh-cn"
  weight = 1

默认网址 显示仍然是英文的

**Comment by shaform** [comment]
Maybe see #92 .

**Comment by lengyueyang** [comment]
defaultContentLanguage = "zh-cn 
默认必须将这一行放到配置文件的第一行，否则默认语言设置不生效

https://discourse.gohugo.io/t/hugo-not-redirecting-to-default-language/10556/5
