### ISSUE TITLE
Error during build: Can't evaluate field RelPermalink

### ISSUE THREAD

**Issue by jackbaty** [xianmin/hugo-theme-jane#222]
Ever since the commit replacing .URL with .RelPermalink I'm getting the following when trying to build with Hugo 0.55.6.

```
ERROR 2019/08/07 10:34:26 render of "home" failed: execute of template failed: template: index.html:11:5: executing "content" at <partial "pagination.html" .>: error calling partial: "/Users/jbaty/sites/blog/themes/hugo-theme-jane/layouts/partials/pagination.html:8:27": execute of template failed: template: partials/pagination.html:8:27: executing "partials/pagination.html" at <.RelPermalink>: can't evaluate field RelPermalink in type *page.Pager
Total in 18680 ms
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:11:5: executing "content" at <partial "pagination.html" .>: error calling partial: "/Users/jbaty/sites/blog/themes/hugo-theme-jane/layouts/partials/pagination.html:17:27": execute of template failed: template: partials/pagination.html:17:27: executing "partials/pagination.html" at <.RelPermalink>: can't evaluate field RelPermalink in type *page.Pager
```

If I change .RelPermalink back to .URL I get the expected .URL deprecation warning, but the site builds. Could very well be something on my end but ¯\_(ツ)_/¯

**Comment by shaform** [comment]
What happens if you only change line 8 & line 17 here to `.URL`, while keeping other `.RelPermalink` intack?

https://github.com/xianmin/hugo-theme-jane/blob/18433ddbbd2cb6442926f822cb5df349680c7fcb/layouts/partials/pagination.html#L8-L17

**Comment by jackbaty** [comment]
> What happens if you only change line 8 & line 17 here to `.URL`, while keeping other `.RelPermalink` intact?

That's what I'd done to get around the error. I still see the deprecation warning but the build works. Thanks.

**Comment by shaform** [comment]
Thanks for reporting back! I guess that might be a bug in 0.55.6 as I don't see the deprecation warning any more in Hugo 0.56.3.
