### ISSUE TITLE
Deployed homepage on Gitlab does not show the list of posts.

### ISSUE THREAD

**Issue by CicoZhang** [xianmin/hugo-theme-jane#229]
After I deployed the site to Gitlab, it does not show the post on the homepage. 
![image](https://user-images.githubusercontent.com/11710225/63124737-44bc9300-bfac-11e9-97a7-9622e5acb088.png)

It works well when I previewed it locally.
![image](https://user-images.githubusercontent.com/11710225/63124768-53a34580-bfac-11e9-82ba-1460018156ba.png)

Does this have something to do with Gitlab Page?

**Comment by CicoZhang** [comment]
This seems to be the issue of Gitlab page. I have redeployed the service to Firebase, it works perfectly now.

**Comment by shaform** [comment]
Looks like to be caused by the problem described in #230.
