### ISSUE TITLE
Add json feed support?

### ISSUE THREAD

**Issue by jostyee** [xianmin/hugo-theme-jane#23]
Introduction: https://jsonfeed.org/

Hugo has already have built-in support: https://bitquabit.com/post/json-feed-with-hugo/

I can send a PR if it's okay for you guys.

**Comment by xianmin** [comment]
Of course, very welcome to pull request. :smile: 

I'm not familiar with the `json feed` . One thing, I think important is, It's better to be optional. 
If somebody doesn't configure it, it's better no side effects.

**Comment by aborruso** [comment]
Hi,
I have uncommented in this way

```
[outputs]
  home = ["html", "jsonfeed"]
  page = ["html"]

[outputFormats]
[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true
```

But I have no json output in public folder.  What's my error?

Thank you

**Comment by jostyee** [comment]
Have you offered a `index.jsonfeed.json` template in your `layouts` directory?

**Comment by aborruso** [comment]
@jostyee  no, I thought they were on the Jane template.

Probably it's better to add a comment in the config.toml (uncomment these line and create index.jsonfeed.json template in your layouts directory).

Thank you, you can close this issue (I will try to create it)
