### ISSUE TITLE
Hugo .57 generates wrong home 

### ISSUE THREAD

**Issue by winsphinx** [xianmin/hugo-theme-jane#231]
after upgrading to Hugo v0.57, the home is only shown a word 'posts', instead of `post lists`.
and downgrading to v0.56, they are fine.
and i found some others have same problem, `even-theme` as well.
examples are many here:
https://themes.gohugo.io/hugo-theme-jane/   , then click demo
https://axdlog.com/
and many others in themes demo: https://themes.gohugo.io/

**Comment by shaform** [comment]
Right, this has been pointed out in #230.
