### ISSUE TITLE
方便使用哪个Search工具？

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#232]
jane theme 对哪个 search工具支持比较好？
 配置文件里提及的 https://cse.google.com/ 国内不能访问吧。

**Comment by xianmin** [comment]
目前只支持 google 。不过已经有了搜索模块，应该比较方便就能添加其他的搜索工具，欢迎 PR :smile: 。

**Comment by luckrill** [comment]
期待 我的理解，搜索 是必须品，评论 是部分人需要

**Comment by winsphinx** [comment]
这个最方便了
https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae

**Comment by luckrill** [comment]
https://verummeum.com/hugo-advanced-features/
我今天看了这个，做了一点操作后，又放弃了 自己状态不佳，比较疲劳

**Comment by luckrill** [comment]
我自己的实现的 站内搜索 https://www.readmorejoy.com/search 
有可能，可以对接到各种各样网站

**Comment by yezihack** [comment]
> 目前只支持 google 。不过已经有了搜索模块，应该比较方便就能添加其他的搜索工具，欢迎 PR 😄 。

config.toml 哪一个配置项

**Comment by luckrill** [comment]
know
