### ISSUE TITLE
mathjax有非常奇怪的问题

### ISSUE THREAD

**Issue by Bennett-Yang** [xianmin/hugo-theme-jane#233]
1. 独立公式内换行有很迷的现象，下面两个公式第一个必须要用六个\才能换行，第二个只用两个：
```
$$
f(x) = \\left\\{
\\begin{aligned}
    &0, x\\leq 0 \\\\\\
    &x,x>0
\\end{aligned}
\\right.
$$
```

```
$$
f(x) = \\left\\{
\\begin{aligned}
    &0, x<0 \\
    &1,x>0
\\end{aligned}
\\right.
$$
```
2. 还有个莫名其妙的问题，下面两个公式第一个可以正常显示，第二个就直接显示为字符了：
```
$$
\begin{align}
\sqrt{37} & = \sqrt{\frac{73^2-1}{12^2}} \\\\\\
a  &= \lim_{x \rightarrow x_0^-} f'(x)
\end{align}
$$
```

```
$$
\begin{align}
a  &= \lim_{x \rightarrow x_0^-} f'(x) \\\\\\
b  &= \lim_{x \rightarrow x_0^+} f'(x)
\end{align}
$$
```
以上公式我都在latex下测试过了（当然是使用两个反斜杠），公式内容我随便写的不必在意。

我觉得可能是hugo渲染markdown对转义字符的处理影响了mathjax？
大佬要是有时间的话还请看一下是怎么回事。谢谢大佬。

**Comment by xianmin** [comment]
@Bennett-Yang 我也觉得这很可能是 Hugo 渲染引擎导致的问题。 LaTeX 方面我不是很熟悉，恐怕没法帮助你。你可以查一下文档看看是否有帮助： https://gohugo.io/content-management/formats/

另外，我新添加了 [KaTeX](https://github.com/KaTeX/KaTeX) ，据测试比 MathJax 更快，你可以试试。

Math Preview 源文件： https://github.com/xianmin/hugo-theme-jane/blob/master/exampleSite/content/post/math-preview.md

Math 公式预览： 
https://www.xianmin.org/hugo-theme-jane/post/math-preview/

**Comment by Bennett-Yang** [comment]
@xianmin  好的，非常感谢，我去试试
