### ISSUE TITLE
What do you think about the new TOC behavior ?

### ISSUE THREAD

**Issue by xianmin** [xianmin/hugo-theme-jane#24]
![deepin-screen-recorder_select area_20180401214415](https://user-images.githubusercontent.com/2177570/38173915-ed394f9a-35f7-11e8-8ea8-5465ed8a900f.gif)

@jostyee @paskal 

When window scroll down, the TOC fadeIn.
It has a fixed position.
When mouse hover it, then show the whole TOC.

**Comment by Avizini** [comment]
Cool!

**Comment by paskal** [comment]
Is it published somewhere to try out? Looks simple and great, I'd love to see it in action.

**Comment by xianmin** [comment]
@paskal I update the develop branch: https://github.com/xianmin/hugo-theme-jane/tree/develop . Maybe you could try it. This new feature still in develop.

**Comment by paskal** [comment]
Feels amazing! I am not able to test it on the phone, but with minimized window it just doesn't show up - if the behavior on the phone is the same and it doesn't break the page, I'm OK.
You're the best.

**Comment by owulveryck** [comment]
I like it a lot!

**Comment by Zebradil** [comment]
Made another option:
![output](https://user-images.githubusercontent.com/1475583/39071494-8e846c10-44e7-11e8-8f7a-4b0c2f22796c.gif)

It is completely based on css, except «scroll-to» functionality.

**Comment by xianmin** [comment]
@Zebradil This looks great! Is there a demo link?

**Comment by Zebradil** [comment]
Yes, I have it in my own site. But currently only one post has TOC. Here is the link: http://ru.zebradil.me/post/2018-04-15-blog-image-optimization/

**Comment by Zebradil** [comment]
I agree. Probably, my version of TOC isn't suitable for the current Jane theme style.
