### ISSUE TITLE
首页空白

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#248]
Hugo升级之后

我遇到首页空白

大家有遇到吗？

![首页空白](https://aws1.discourse-cdn.com/standard10/uploads/gohugo/original/2X/b/b18df87a2b45d37d28c20b5078e336b682336494.png)

**Comment by jackbaty** [comment]
I'm having the same problem (Hugo 0.58.2). I think this is due to changes in Hugo 0.58 and changing `.Data.Pages` to `.Site.RegularPages` in `./layouts/index.html` fixed the problem for me. (found here: https://discourse.gohugo.io/t/home-blank/20818/4)

**Comment by shaform** [comment]
It has been fixed in this PR https://github.com/xianmin/hugo-theme-jane/pull/230.
You should update the theme to the latest version.

**Comment by jackbaty** [comment]
Ah, sorry, I thought I was already on latest but missed this one. Thanks!
