### ISSUE TITLE
main.js 加载失败

### ISSUE THREAD

**Issue by wingsxdu** [xianmin/hugo-theme-jane#252]
![image](https://user-images.githubusercontent.com/47047644/65936240-9632bb80-e44e-11e9-81c5-69a7c58a079b.png)
main.js 文件加载失败,导致菜单键和目录无法使用.
我已经按照[issue #208 ](https://github.com/xianmin/hugo-theme-jane/issues/208),使用 hugo-extended 版本,这不起作用

**Comment by xianmin** [comment]
看一下这个链接 https://github.com/xianmin/hugo-theme-jane/issues/143 ，是否可以解决呢？

**Comment by wingsxdu** [comment]
> 看一下这个链接 #143 ，是否可以解决呢？

感谢,正常了
