### ISSUE TITLE
How to widen page?

### ISSUE THREAD

**Issue by winsphinx** [xianmin/hugo-theme-jane#258]
It seems the page width is too narrow, which is about 60% of a web. I guess that would maybe 75%~80% is better. How could I adjust the width?

**Comment by fish47** [comment]
create file under the blog project root if not exist
`assets/sass/_custom/_custom.scss`
and insert variable declaration like this
`$global-body-width: 1300px;`

**Comment by winsphinx** [comment]
Great! Thank you. :+1:
