### ISSUE TITLE
如何实现每个页面带有一个隐藏的图片

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#275]
方便转发文章时候，这个图片可以做 缩略图 用途

**Comment by shaform** [comment]
理論上 `<meta property="og:image"  ...` 就是用來做這個用途，而且 Jane 應該已有支援: https://gohugo.io/templates/internal/#configure-open-graph

**Comment by luckrill** [comment]
增加了 images = ["site-feature-image.jpg"] 
从页面代码上看是支持了 

但分享后，发现显示的仍然是  打赏图片 作为了缩略图

**Comment by luckrill** [comment]
know
