### ISSUE TITLE
某篇文章的 categories 正文链接正常而英文链接不正常

### ISSUE THREAD

**Issue by choicky** [xianmin/hugo-theme-jane#279]
我最近发表了一篇 《[证券法（2019年修订）](https://itlaws.cn/post/securities-laws-2019/)》，使用的`categories`是：
```
categories: [
    "Laws",
    "法律全文",
]
```

现在发现的问题是：
https://itlaws.cn/categories/法律全文/ 能找到这篇文章，

https://itlaws.cn/categories/laws/ 找不到这篇文章。

其他 post 没发现这个问题。例如 《[个人所得税法](https://itlaws.cn/post/personal-income-tax-law-2018/)》没发现这个问题。 `categories` 的设置是一样的。

**Comment by shaform** [comment]
點進去 https://itlaws.cn/categories/laws/ 似乎找的到該篇文章？

**Comment by choicky** [comment]
> 
> 
> 點進去 https://itlaws.cn/categories/laws/ 似乎找的到該篇文章？

呃。。。 我发现 chrome 能找到那篇文章， firefox 找不到... 
我用的是 firefox 73.0b7

**Comment by choicky** [comment]
呃，我知道了， firefox 缓存了页面，没有刷新....
