### ISSUE TITLE
Why chose client-side code highlighting over builtin server-side func?

### ISSUE THREAD

**Issue by jostyee** [xianmin/hugo-theme-jane#28]
Hugo does support [code highlighting](https://gohugo.io/content-management/syntax-highlighting/) since version 0.28 adopted from Chroma, by which we don't need the highlight javascript library to do the job, I wonder why @xianmin chose not to use it?

Some other themes for comparison:
- [beautifulhugo](https://github.com/halogenica/beautifulhugo): server/client side options
- [hugo-nuo](https://github.com/laozhu/hugo-nuo): Chroma
- [hugo-kiera](https://github.com/avianto/hugo-kiera): Chroma

**Comment by xianmin** [comment]
Thanks for your feedback!
This project Initial version is [olOwOlo/hugo-theme-even](https://github.com/olOwOlo/hugo-theme-even/). Hugo-theme-even use `highlight.js` library, and for me, the style of the show is not bad. So I did not modify it.

I haven't tested the =Chroma= yet. Maybe we can try it?  :smile:

**Comment by jostyee** [comment]
Yeah, I guess it’s not complicated to add Chroma support.

**Comment by jostyee** [comment]
IMHO server-side highlighting pros:
1. faster loading time
2. less 3rd-party dependencies, make it easier to maintain
3. friendly to some readability services(e.g. Instapaper cannot parse highlight.js code block properly)

while client-side highlighting can:
1. render more language syntaxes for now.

**Comment by xianmin** [comment]
Yes, less 3rd-party dependencies is better. 
If we choose `Chroma` finally, and if anyone still want use `highlight.js` , I think he could use `custom head` and `custom.js` do it.

The `highlight.js` works fine for now. If you are interested in switch to `Chroma`, maybe you could try it first, and I am very supportive. :smile:

**Comment by jostyee** [comment]
@xianmin You've hardcoded highlight invocations in `main.js` , which cannot be changed by config checks.

**Comment by xianmin** [comment]
If `Chroma` works fine, maybe we could remove all `highlight.js` related code.
Or put it on hold first, wait for me to deal with this later.

**Comment by jostyee** [comment]
@Zebradil I'm currently busy at my work, please give it a go if you have time, thanks.

**Comment by Zebradil** [comment]
@jostyee, I'll go for it this week then.

**Comment by jostyee** [comment]
@Zebradil great work, thanks.
@xianmin Chroma has multiple syntax highlighting presets itself, see: https://help.farbox.com/pygments.html with `pygmentsUseClasses = false`

**Comment by Zebradil** [comment]
Another way to change style is to use hugo's `gen` command:
```
hugo gen chromastyles --style=native > style.css
```
With this approach it's possible to tune highlight style manually.
