### ISSUE TITLE
发布后 日期错误 是怎么回事昵？

### ISSUE THREAD

**Issue by luckrill** [xianmin/hugo-theme-jane#280]
我这两天刚刚编辑发布的文章，
编辑模式里 日期正确
---
title: "我，我们，能做点帮助武汉疫情事情吗？"
date: 2020-02-01T11:28:54+08:00
lastmod: 2020-02-01T11:28:54+08:00

发布之后，时间就错误了，什么地方出的问题昵？

![QQ20200202-193224](https://user-images.githubusercontent.com/5372899/73607609-467a2180-45f3-11ea-943d-0c78e82c75aa.png)

网站地址 https://www.readmorejoy.com/

**Comment by luckrill** [comment]
the reason is: dateFormatToUse = “2006-01-02”

I have modify it as dateFormatToUse = “2006-03-09”

must as https://gohugo.io/functions/format/

**Comment by shaform** [comment]
What's the difference between these two?
