### ISSUE TITLE
归档最后为什么出现一个0001的归档呢?

### ISSUE THREAD

**Issue by yezihack** [xianmin/hugo-theme-jane#297]
https://www.sgfoot.com/post.html
![image](https://user-images.githubusercontent.com/11530866/80199389-d5776280-8653-11ea-8672-0c930b6002c9.png)

**Comment by Nick17t** [comment]
因为是时间线的错乱，可以在post文件夹里的文章头部修改就可以的。
---
title: "example"
date: 2020-04-17T20:43:57+08:00
description: ""
draft: false
---
