### ISSUE TITLE
how  can i use git commit date as the last modify date 

### ISSUE THREAD

**Issue by ileeoyo** [xianmin/hugo-theme-jane#299]

**Comment by shaform** [comment]
You should set
```
enableGitInfo = true
```
in your config.toml

**Comment by ileeoyo** [comment]
I have  already set config `enableGitInfo = true`.but it did not work,the lastMod won't change automatically

**Comment by ileeoyo** [comment]
solved
[https://github.com/gohugoio/hugo/issues/3071](https://github.com/gohugoio/hugo/issues/3071)
