### ISSUE TITLE
如果能选择颜色方案，就更好了。

### ISSUE THREAD

**Issue by choicky** [xianmin/hugo-theme-jane#307]
这款 theme 挺好的，我持续用了好几年了。

也是因为用了好几年，所以有点审美疲劳了。忽然感觉颜色有点单调。

如果能提供几种配色方案就更好了，审美疲劳时可以更换其他的颜色。

**Comment by sosiristseng** [comment]
You mean something like this? [Color your world theme](https://color-your-world-demo.netlify.app/)

**Comment by newdivide2014** [comment]
啥时候能有dark mode啊？
