### ISSUE TITLE
youtube and twitch missing from socials?

### ISSUE THREAD

**Issue by gilmirmo** [xianmin/hugo-theme-jane#313]
I'm trying to add youtube and twitch to my socials, but I can't just add it to the config.

how do I do that?

**Comment by big-mon** [comment]
maybe, needs their logo icon as `.svg`.
If you have icons, I could write code.

like
```
<svg
  class="icon" style="" viewBox="0 0 1024 1024" version="1.1" width="36"
  height="36" id="svg8">
  <path
      style=""
      d="PATHPATHPATHPATH"
      id="rect824"/>
</svg>
```

**Comment by gilmirmo** [comment]
no `.svg` but youtube offers  [brand resources and guidelines](https://www.youtube.com/about/brand-resources/#logos-icons-colors) as `.png` `.eps` and `.ai`

[Twitch Brand Resources](https://brand.twitch.tv/downloads/twitch-brand-assets.zip) do have `.svg` though

**Comment by big-mon** [comment]
I sent pull request to reviewer. #314 
So, you can copy that code or wait merge.

I tried selef check. it's works.

**Comment by gilmirmo** [comment]
thanks a lot :)
