### ISSUE TITLE
How to add icon to notice shortcode title bar?

### ISSUE THREAD

**Issue by winux1** [xianmin/hugo-theme-jane#317]
Hello!
I would like to know how can I make the notice shortcode look like the same as on the picture (add icon)

![image](https://user-images.githubusercontent.com/73439774/107854583-12982580-6e1d-11eb-8bf8-ebbfbeaf58d9.png)

Thanks for your help in advance!

The picture was taken from here: https://github.com/martignoni/hugo-notice

**Comment by wzc0x0** [comment]
You can build in your project. This theme could be abandoned

**Comment by winux1** [comment]
Thanks! It works!
