### ISSUE TITLE
Show list of available translations in the Menu

### ISSUE THREAD

**Issue by xianmin** [xianmin/hugo-theme-jane#32]
Thanks for @Zebradil ! His pull request #27 add a feature: Show available translations under post title.

<img width="901" alt="screen shot 2018-04-03 at 23 51 23" src="https://user-images.githubusercontent.com/1475583/38277848-2926ea5a-379a-11e8-977a-65bd9613cd95.png">

I think, if a site is Multilingual site, it's best to switch languages somewhere and show available languages.
Maybe in the rightmost of Menu.

This proposal need sub menu #31  support first.

**Comment by shaform** [comment]
Is `mobile-menu` supposed to support drop down menu?

I am trying to add this feature to my site as well. My current progress:

```patch
+++ b/layouts/partials/header.html
@@ -38,5 +38,18 @@
 
       </li>
     {{ end }}
+    {{ if gt (len .Site.Home.AllTranslations) 1 }}
+      <li class="menu-item">
+        <!-- drop down navigation MENU -->
+        <a class="menu-item-link menu-parent" href="{{ .URL | absLangURL | safeURL }}">{{ i18n "language" }}</a>
+        <ul class="submenu">
+          {{ range .Site.Home.AllTranslations }}
+            <li>
+              <a href="{{ .Permalink }}">{{ .Language.LanguageName }}</a>
+            </li>
+          {{ end }}
+        </ul>
+      </li>
+    {{ end }}
   </ul>
 </nav>
+++ b/layouts/partials/slideout.html
@@ -23,5 +23,17 @@
         </a>
       </li>
     {{- end }}
+    {{ if gt (len .Site.Home.AllTranslations) 1 }}
+      <li class="mobile-menu-item">
+        {{ i18n "language" }}
+        <ul class="submenu">
+          {{ range .Site.Home.AllTranslations }}
+            <li>
+              <a href="{{ .Permalink }}">{{ .Language.LanguageName }}</a>
+            </li>
+          {{ end }}
+        </ul>
+      </li>
+    {{ end }}
+++ b/i18n/en.yaml
@@ -95,3 +95,7 @@
 
 - id: read_fr
   translation: Lire en français
+
+- id: language
+  translation: Language
```

**Comment by xianmin** [comment]
@shaform Yes, `mobile-menu` should support drop down menu. I will do this next step.

Your progress looks good! But I have a little doubt about "how to display language menu better".
Maybe like this site: https://www.duolingo.com/ ? I am not sure.

Most users just use two languages. They can add a language link to the menu easily.

So, my point is, it's better add an **option** to show available translations in the menu.

Thanks for your progress. Welcome to PR! :smile:

**Comment by xianmin** [comment]
Thanks for @shaform ! Now, hugo-theme-jane could show list of languages in the menu.

To enable this feature, you need add an option `showMenuLanguageChooser = true` to your site config file.
