### ISSUE TITLE
Dark code block on white website

### ISSUE THREAD

**Issue by paskal** [xianmin/hugo-theme-jane#340]
Hi there!

I'm adding the following text to my post:

    ```yaml
    # test
    ```

Here is what I see on the latest macOS with a dark theme both in Safari and Chrome:

<img width="988" alt="image" src="https://user-images.githubusercontent.com/712534/180885908-d92d40b8-e262-4d01-b6c7-9481e81ab0fa.png">

White stripes point towards the fact that "background" is overwritten to white (`#f8f5ec` to be precise) somewhere but in the wrong place.

**Comment by M4THYOU** [comment]
any fix for this? I'm seeing the same problem

**Comment by M4THYOU** [comment]
Solution is in #133

You need to add those lines to your `config.toml`.

**Comment by paskal** [comment]
`PygmentsUseClasses = true` helped me, thanks for the hint!
