### ISSUE TITLE
In 58d7b87, code block without language looks weird

### ISSUE THREAD

**Issue by CyrusYip** [xianmin/hugo-theme-jane#343]
Solution: https://github.com/xianmin/hugo-theme-jane/issues/343#issuecomment-1242673329

I use hugo v0.99.1.

```
❯ hugo version
hugo v0.99.1-d524067382e60ce2a2248c3133a1b3af206b6ef1+extended linux/amd64 BuildDate=2022-05-18T11:18:14Z VendorInfo=gohugoio
```

Reproducible example:

```
git clone https://github.com/xianmin/hugo-theme-jane.git
cd hugo-theme-jane
git reset --hard 58d7b87
hugo server --contentDir='./exampleSite/content' --config='dev-config.toml'
```

Visit `http://localhost:43909/hugo-theme-jane/post/syntax-highlighting/` in your browser (change `43909` into the port used by your system).

Code blocks with language look normal. Those without language look weird.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/60951091/189075018-2a729fea-3d21-4b2c-bf64-b37dff053979.png">

The example file is `exampleSite/content/post/syntax-highlighting.md`.

<details>
<summary>Excerpt</summary>

````
```scala
object HelloWorld with Application {
  Console.println("Hello, World!");
}
```

```php
<?php
  echo 'Hello, World!';
?>
```

```python
print("Hello, World!")
```

## no named code block

```
## this is a comment
$ echo this is a command
this is a command

## edit the file
$vi foo.md
+++
date = "2014-09-28"
title = "creating a new theme"
+++

bah and humbug
:wq

## show it
$ cat foo.md
+++
date = "2014-09-28"
title = "creating a new theme"
+++

bah and humbug
$
```

````
</details>

**Comment by xianmin** [comment]
yes, it's a problem, I wiil think about if there is a good solution. Thank you for your feedback! 😃

**Comment by oe7drt** [comment]
It would fall back to "fallback" language when `guessSyntax = true` is set in config file.

```toml
[markup]
  [markup.highlight]
    guessSyntax = true
```
![grafik](https://user-images.githubusercontent.com/10201502/189476445-6afc1285-04c2-498d-94ee-c779c3b2030a.png)

**Comment by CyrusYip** [comment]
@oe7drt Your solution works. Thank you.
