### ISSUE TITLE
我都以为你放弃了。。。。。

### ISSUE THREAD

**Issue by user1121114685** [xianmin/hugo-theme-jane#348]

**Comment by user1121114685** [comment]
还好我没放弃 这就把博客更新一下

**Comment by user1121114685** [comment]
`rel="noreferrer"`
大佬请问能不能在图片请求中添加个这个，取消Referer gitee 不让使用带有Referer的地址了

**Comment by xianmin** [comment]
我自己一直在用，所以还没弃坑……精力有限，只能想改了就改一改。

你这个图片的问题很好解决啊，自己写个的 shortcode 就行了

**Comment by user1121114685** [comment]
> 我自己一直在用，所以还没弃坑……精力有限，只能想改了就改一改。
> 
> 你这个图片的问题很好解决啊，自己写个的 shortcode 就行了

谢谢大佬，不过我不懂js html css 所以不知道如何出手。

**Comment by Ionizing** [comment]
> > 我自己一直在用，所以还没弃坑……精力有限，只能想改了就改一改。
> > 你这个图片的问题很好解决啊，自己写个的 shortcode 就行了
> 
> 谢谢大佬，不过我不懂js html css 所以不知道如何出手。

我搜了一下， `class="img"` 定义在 `themes/jane/layouts/shortcodes/figure.html` 第 15 行，它下面就是 `<a href="link-to-fig">`
```html
    <div class="img"{{ if .Parent }} style="background-image: url('{{ print $thumb }}');"{{ end }}{{ with .Get "size" }} data-size="{{.}}"{{ end }}>
      <img itemprop="thumbnail" src="{{ $thumb }}" {{ with .Get "alt" | default (.Get "caption") }}alt="{{.}}"{{ end }}/><!-- <img> hidden if in .gallery -->
    </div>
    {{ with .Get "link" | default (.Get "src") }}<a href="{{.}}"{{ with $.Get "target" }} target="{{.}}"{{ end }}{{ with $.Get "rel" }} rel="{{.}}"{{ end }} itemprop="contentUrl"></a>{{ end }}
```
所以在这里面加上 `rel="noreferrer"` 应该能解决楼主的问题？

**Comment by user1121114685** [comment]
> > > 我自己一直在用，所以还没弃坑……精力有限，只能想改了就改一改。
> > > 你这个图片的问题很好解决啊，自己写个的 shortcode 就行了
> > 
> > 
> > 谢谢大佬，不过我不懂js html css 所以不知道如何出手。
> 
> 我搜了一下， `class="img"` 定义在 `themes/jane/layouts/shortcodes/figure.html` 第 15 行，它下面就是 `<a href="link-to-fig">`
> 
> ```
>     <div class="img"{{ if .Parent }} style="background-image: url('{{ print $thumb }}');"{{ end }}{{ with .Get "size" }} data-size="{{.}}"{{ end }}>
>       <img itemprop="thumbnail" src="{{ $thumb }}" {{ with .Get "alt" | default (.Get "caption") }}alt="{{.}}"{{ end }}/>
>     </div>
>     {{ with .Get "link" | default (.Get "src") }}<a href="{{.}}"{{ with $.Get "target" }} target="{{.}}"{{ end }}{{ with $.Get "rel" }} rel="{{.}}"{{ end }} itemprop="contentUrl"></a>{{ end }}
> ```
> 


> 所以在这里面加上 `rel="noreferrer"` 应该能解决楼主的问题？

谢谢你，这个问题快两年了终于得到了解决，非常感谢你的帮助


![Snipaste_2023-03-09_19-58-02](https://user-images.githubusercontent.com/28774851/224016502-785f67ac-6632-4c26-811b-00ee296d8651.png)


同时也感谢bing的帮助，


修改 jane\layouts\partials\head.html


在16-20行之间全部都是全局配置（我猜），
然后增加一行输入 `<meta name="referrer" content="no-referrer" />`



![Snipaste_2023-03-09_20-01-33](https://user-images.githubusercontent.com/28774851/224017274-ec962270-02d2-41ce-ba30-62729c5ecac6.png)

**Comment by user1121114685** [comment]
@xianmin 好久不见

**Comment by xianmin** [comment]
@user1121114685 哈哈，处理几个 PR
