### ISSUE TITLE
模板日志是有问题吗

### ISSUE THREAD

**Issue by comor86** [xianmin/hugo-theme-jane#363]
$ hugo server
Start building sites …
hugo v0.113.0-085c1b3d614e23d218ebf9daad909deaa2390c9a+extended windows/amd64 BuildDate=2023-06-05T15:04:51Z VendorInfo=gohugoio
Built in 69 ms
Error: error building site: assemble: "D:\hugo\sites\comor.cn\content\post\demo\6-shortcode-notice.md:25:1": failed to extract shortcode: template for shortcode "notice" not found

**Comment by cometlj** [comment]
我也抓过问题 你解决了吗？

**Comment by xianmin** [comment]
请提供更详细的信息，谢谢！
