### ISSUE TITLE
Site.Author is deprecated in favour of Params.author in Hugo v0.120.2

### ISSUE THREAD

**Issue by paskal** [xianmin/hugo-theme-jane#369]
Hello!

`hugo` with version [0.120.2 and newer](https://github.com/gohugoio/hugo/blob/a7e721e02df842218c7ecf739daab01002113287/tpl/tplimpl/embedded/templates/_default/rss.xml#L1-L31) says following on the build:

    WARN  The author key in site configuration is deprecated. Use params.author.email instead.
    WARN  The author key in site configuration is deprecated. Use params.author.name instead.

This theme should be altered to use `Params.author` as a fallback if `Site.Author` (keys `name`, `email` and `url`) is absent. The problem is that `Params.author` is already used as a substitute for `Site.Author.name` in this theme, so it would be a breaking change to remove all the old key usages in favour of using only `Params.author.name` and `Site.Author.name`.

I'll prepare the changes, and I guess I'll add throwing an error if `Params.author` is present as a string so that it will break explicitly and the theme users would be fully aware of what they need to change to make it work.

**Comment by ventz** [comment]
Came here to post about exactly this too! (@paskal Thank you for the detailed description.)

**Comment by paskal** [comment]
Figuring out if `Params.author` is set but is string and not a trivial task, see [reflect.IsSlice](https://gohugo.io/functions/reflect/isslice/) and [this discussion](https://discourse.gohugo.io/t/how-to-check-if-a-variable-is-string-or-array/7460/7) for reference.

**Comment by xianmin** [comment]
Thank you @paskal for fixing this issue, it has been merged into master. sorry for the late reply......
