### ISSUE TITLE
Outdated version of MathJax

### ISSUE THREAD

**Issue by sboukortt** [xianmin/hugo-theme-jane#377]
Hi,

It seems that the theme is using a version of MathJax that is quite old by now. Perhaps we should consider upgrading it?

I tried, locally, to just update:

https://github.com/xianmin/hugo-theme-jane/blob/baa2b23d3151037394c0737b29ea3baf98506621/layouts/partials/scripts.html#L27

to instead point to `https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js`, and it seems to work without any obvious issue.

Thanks.

**Comment by sboukortt** [comment]
(For what it’s worth, https://www.mathjax.org/#gettingstarted suggests also adding a polyfill.)

**Comment by xianmin** [comment]
Haha, indeed. if you are willing, welcome to submit a PR! 😄
