### ISSUE TITLE
hugo 生成静态网页渲染问题

### ISSUE THREAD

**Issue by AriesChen-UPC** [xianmin/hugo-theme-jane#380]
利用 hugo server 本地查看正常，利用 hugo 生成静态网页，静态网页格式有问题，请问是什么原因呢？

<img width="199" alt="CleanShot 2024-03-26 at 10 30 04@2x" src="https://github.com/xianmin/hugo-theme-jane/assets/61337898/b3906a84-ff5b-4bc9-8603-f204c2cc60fe">

hugo version：v0.124.1
go version：1.22.1
macOS：14.4

**Comment by xianmin** [comment]
你在浏览器按 F12 ，看看 Console 有没有报错？

**Comment by AriesChen-UPC** [comment]
谢谢，我尝试一下
