### ISSUE TITLE
"zh-CN" is an invalid value for defaultContentLanguage

### ISSUE THREAD

**Issue by youkpter** [xianmin/hugo-theme-jane#4]
In readme.md, the config value of defaultContentLanguage is `"zh-CN"`. When run:
```
hugo server
```
It will produce an error:
> Error: site config value "zh-CN" for defaultContentLanguage does not match any language definition

If we change the value to `"zh-cn"`, it will be OK. Maybe we should fix it in readme.md.

**Comment by xianmin** [comment]
@youkpter What's your OS？ In my Linux environment, "zh-CN" & "zh-cn" are OK.
But in other platform, I'm not sure.

**Comment by youkpter** [comment]
My OS is Ubuntu 14.04.
I tried set defaultContentLanguage to "EN", it produced the same error.

**Comment by jostyee** [comment]
`zh-cn` is standard identifier according to http://www.rssboard.org/rss-language-codes

**Comment by xianmin** [comment]
@jostyee I found the reason. [Lowercase default lang when checking if it exists by kyoshino · Pull Request #4342 · gohugoio/hugo](https://github.com/gohugoio/hugo/pull/4342)
`defaultContentLanguage` option can only be lowercased in new Hugo version.
This option is **not related to standards** .

**Comment by xianmin** [comment]
@youkpter Thank you for your feedback! I have updated the documentation.

**Comment by kyoshino** [comment]
I'd rather like to see the bug fixed...

**Comment by kyoshino** [comment]
Aside from this specific bug, Hugo doesn’t handle `ab-CD` style lang codes properly. I have a [dozen of hardcoded replacer](https://github.com/fxsitecompat/www.fxsitecompat.com/search?l=HTML&q=en-CA) to make `en-CA` links work.

**Comment by adrian-cy** [comment]
@xianmin I just hit the issue today and it's still not fixed. the pull request you referenced never went through as the user that submitted it never accepted the Contributor License Agreement.
