### ISSUE TITLE
Some issues about v3

### ISSUE THREAD

**Issue by razonyang** [xianmin/hugo-theme-jane#401]
Hi, I noticed that the theme uses `hugomods/icons` since version 3, because it's modular, I'm afraid that the git-way installation on README (clone theme into themes folder) may no longer valid, users have to use Hugo module to install theme.

> The `hugomods/icons` vendor modules mount SVG icons from GitHub repositories into `assets` folder, which might not possible (or very complex) when installed via Git (clone or submodule).

If Hugo Modules is adopted by v3, the module path may need to be updated as well.

I haven't created PRs yet because I'm not sure if the theme will ultimately choose modularization.

**Comment by xianmin** [comment]
Thank you for your reminder.
The current issue is a bit beyond my expectations.
I didn't consider that using Hugo modules would require installing the Go language environment, as I already had Go installed on my computer. 
If this is the case, I might need to think about it more carefully. 
It's possible that removing the Hugo modules might be a better option... I don't want installing Go to be a must choice.

**Comment by razonyang** [comment]
> It's possible that removing the Hugo modules might be a better option...

Yeah, it's possible if you [vendor modules within the theme](https://github.com/razonyang/hugo-theme-jane/commits/master/), but the downside is that the repository will become very large to include all the required modules (in this case, 10+K icons was included into the theme repo).

But it doesn't seem meaningful to modularize if you only need the icons functionality.
