### ISSUE TITLE
A leading space in mobile_header.html will cause a 404 error

### ISSUE THREAD

**Issue by p0n1** [xianmin/hugo-theme-jane#406]
https://github.com/xianmin/hugo-theme-jane/blob/74738feedf60189984059a32735a39b9388a3509/layouts/partials/mobile_header.html#L11-L13

I think the `" /"` should be `"/"`. Similar to #404.

**Comment by xianmin** [comment]
I figured out why it was causing this problem, because I was using [prettier-plugin-go-template](https://github.com/NiklasPor/prettier-plugin-go-template) for format files, which I hadn't noticed.

**Comment by xianmin** [comment]
Switching to backticks <code>`</code> now avoids being reformatted.

**Comment by p0n1** [comment]
Nice. Thanks!
