### ISSUE TITLE
Support Gitalk

### ISSUE THREAD

**Issue by Jancat** [xianmin/hugo-theme-jane#41]
Provide [Gitalk](https://gitalk.github.io/) comment support.

**Comment by jostyee** [comment]
Currently Gitalk has a serious issue: https://github.com/gitalk/gitalk/issues/102

**Comment by xianmin** [comment]
Useful link: [add gitment module by sslyxhz · Pull Request #36 · olOwOlo/hugo-theme-even](https://github.com/olOwOlo/hugo-theme-even/pull/36)

**Comment by xianmin** [comment]
Now, Jane-theme support utterances comment which I think is better comment base on github issues.

https://github.com/xianmin/hugo-theme-jane/issues/74
