### ISSUE TITLE
Support blog slogan

### ISSUE THREAD

**Issue by Jancat** [xianmin/hugo-theme-jane#42]
Support to config `slogan` in the header bar.

**Comment by Zebradil** [comment]
@Jancat Can you provide some design examples?

**Comment by Jancat** [comment]
@Zebradil Just looking for a few：
http://colobu.com/
http://blog.devtang.com/
https://coolshell.cn/

Keep simple and elegant.

**Comment by Zebradil** [comment]
Need to think about it. Currently, we have pretty narrow top panel. Probably, we can make it higher and place slogan under logo, but only for wide screens. @xianmin what do you think about it?

**Comment by Jancat** [comment]
Thanks. It seemed worth a try. @xianmin
