### ISSUE TITLE
Portuguese translation

### ISSUE THREAD

**Issue by RicardoDanielGonzalez** [xianmin/hugo-theme-jane#47]
Hey guys!
First of all, many thanks [for your](https://themes.gohugo.io/hugo-theme-jane/) incredible work.
2nd: I don't know nothing about code, but I love [Hugo](https://gohugo.io) and [Markdown](https://daringfireball.net/projects/markdown/).
3rd: I'm running a [multilingual site](https://ricardodgonzalez.com). And I've achieved this because **you made this easier.** Spanish is the default language, alongside English and Portuguese. I've made some changes on your Spanish i18n file, and developed the Portuguese one.
I've attached the files on txt, because is the shortest way I've found to do this, so far.
[es.txt](https://github.com/xianmin/hugo-theme-jane/files/1947889/es.txt)
[pt.txt](https://github.com/xianmin/hugo-theme-jane/files/1947890/pt.txt)
Best regards!
See you soon!
And, again, many thanks!
Ricardo

**Comment by xianmin** [comment]
Hi @RicardoDanielGonzalez !
Thanks for your translation! 
According to your translation, I have added the Portuguese to the repository, 
I have a question: How to translate "Read in Portuguese"? Google translate it "Leia em português", Is this correct?

Best regards!
