### ISSUE TITLE
Does anyone need twitter emoji parser?

### ISSUE THREAD

**Issue by xianmin** [xianmin/hugo-theme-jane#55]
For now, if you set `enableEmoji = true` in your site’s configuration, hugo will parse the emoji like this:

![deepinscreenshot_select-area_20180505105358](https://user-images.githubusercontent.com/2177570/39659130-3e18ea12-5054-11e8-96d6-45cfd9b85eeb.png)

l find a library: https://github.com/twitter/twemoji

If you use `twemoji`, your site's emoji could convert unicode to image, like this:

![deepinscreenshot_select-area_20180505105328](https://user-images.githubusercontent.com/2177570/39659178-818b6878-5055-11e8-8a38-63ffc505f4e0.png)

If anyone like this feature, maybe I can consider adding an option to use it.

**Comment by Zebradil** [comment]
I'd like to render emoji on client side only if there are no native support. Personally, I like Apple style more. However, it could be better to have the same style on any platform, because in different styles the same emoji could represent lightly different meaning.
