### ISSUE TITLE
image preview doesn't work in normal image mode while photoswipe is enable

### ISSUE THREAD

**Issue by MaxdSre** [xianmin/hugo-theme-jane#58]
While I enable directive **`photoswipe`** in file `config.toml`, image preview doesn't work in normal image mode

```
![This is an image in `static/image` folder.](/image/example.jpg)
```

But images can be previewed via **`{{< figure >}}`** shortcode.

```
{{</* figure src="/image/example.jpg" title="figure image with title" */>}}
```

Does theme `jane` doesn't support image preview in normal image mode any more?

**Comment by xianmin** [comment]
This problem is caused by `load-photoswipe.js`.
If we want to solve it, maybe the best way is:

convert
```html
<p>
  <img src="/hugo-theme-jane/image/example.jpg" alt="This is an image in `static/image` folder.">
</p>
```
to
```html
<figure itemprop="associatedMedia" itemscope="" itemtype="http://schema.org/ImageObject">
  <div class="img">
    <img itemprop="thumbnail" src="http://localhost:1313/hugo-theme-jane/image/example.jpg" alt="This is an image in `static/image`">
  </div>
  <a href="http://localhost:1313/hugo-theme-jane/image/example.jpg" itemprop="contentUrl"></a>
  <figcaption>
    <p>This is an image in `static/image`</p>
  </figcaption>
</figure>
```

In other words, unified the html code of the image.

What do you think? @Zebradil

**Comment by Zebradil** [comment]
Was it supported before we migrated to photoswipe? If we broke something, it's better to fix it. If it worked in the same before the migration, we can leave it as is.

**Comment by xianmin** [comment]
I have fixed this issue.
