### ISSUE TITLE
`autoCollapseToc` config doesn't work

### ISSUE THREAD

**Issue by jostyee** [xianmin/hugo-theme-jane#6]
Tried `autoCollapseToc = true` but toc still shows unfolded.

**Comment by xianmin** [comment]
This function `autoCollapseToc` from `Hugo-theme-even` was removed by me.
I am thinking about how to display it better when Toc is folded.

**Comment by paskal** [comment]
Here is approach I like a lot: https://scripter.co/hugo-leaf-and-branch-bundles/

**Comment by paskal** [comment]
Another design suggestion I have is have images slightly bigger than text: it looks amazing. [Casper](https://github.com/vjeantet/hugo-theme-casper) ([source code](https://github.com/vjeantet/hugo-theme-casper/blob/master/static/css/screen.css)) theme does that:
https://vjeantet.fr/retour-dexperience-hackathon-societe-generale/
https://vjeantet.fr/docker-io-paris-meetup-5/
https://vjeantet.fr/golang-chez-google/
https://terrty.net/images/hugo_themes/casper_single_post.png

And another one, [Whiteplain](https://github.com/taikii/whiteplain) ([source code](https://github.com/taikii/whiteplain/blob/master/layouts/_default/terms.html)) have amazing tags which have all the metadata possible on it:
https://themes.gohugo.io/theme/whiteplain/tags/
https://terrty.net/images/hugo_themes/whiteplain_tags.png
Could you please make a tooltip (alt text) on tag with a date of the last post in the tag? I don't know how well it will look and feel like but I think it's worth a try.

**Comment by xianmin** [comment]
@paskal  Thank you very much for the information you provided! I will refer to them.

**Comment by xianmin** [comment]
I updated the new TOC behavior, Welcome to try!
