### ISSUE TITLE
Could someone explain how to apply the custom.css

### ISSUE THREAD

**Issue by riesthorsten** [xianmin/hugo-theme-jane#61]
More a howto question than an issue really:
I would like to use Jane for my personal website, it is fantastic. I only struggle with applying custom.css. I found the definition in config.toml and put a custom.css in the approriate place(s), but the rendering doesn't seem to change upon "hugo server". Does someone have a minimal example how it works?

**Comment by xianmin** [comment]
What is your `customCSS` config in config.toml?

Here is an example : [change logo font](https://github.com/xianmin/hugo-theme-jane/issues/7)

**Comment by riesthorsten** [comment]
Thanks for the link to the change logo font manual, which I overlooked. It works now after it reminded me that I have to put the import line as well.

**Comment by xianmin** [comment]
If you have any questions, welcome to ask.
