### ISSUE TITLE
npm run dev:assets failing due to TypeError

### ISSUE THREAD

**Issue by juanwolf** [xianmin/hugo-theme-jane#63]
I was trying to build the theme on my dev environment (OS: ArchLinux) but I've got this weird error:

```bash
$ npm run dev:assets                                                                                                                                                

> hugo-theme-jane@1.2.0 dev:assets /home/my_user/projects/jane
> webpack --watch --display='errors-only'


Webpack is watching the files…

(node:23444) UnhandledPromiseRejectionWarning: TypeError: Cannot create property 'message' on string 'Checksum error in glyf'
    at /home/my_user/projects/jane/node_modules/iconfont-webpack-plugin/lib/loader.js:34:19
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23444) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I looked at the "iconfont-webpack-plugin" repo and no issue were reported about this problem, so I am wondering if it's not related to my local installation...

I'll continue to investigate and update this issue if I find anything.

**Comment by Zebradil** [comment]
Firstly, try to run 

```shell
$ npm rebuild node-sass --force
```

If it doesn't help or if the issue appears again later, try to set up node virtual environment for older version of node.

I also faced this problem some time ago and I figured out that some of dependencies (which we can't change directly) is not ready for new version of node.
I have node version `v9.11.1`, npm version `5.10.0`.

**Comment by juanwolf** [comment]
Thanks a lot for the quick response. That would explain why it worked on my mac but not on Arch... The command did not help.

I installed a new node env and it worked :smile: 

In case anyone is having the issue:

```
sudo pip install nodeenv
nodeenv env --node 9.11.1 #This will create a new env folder in your current dir
source env/bin/activate
npm rebuild node-sass --force
npm run dev:assets #It works :D :D :D 
```

Thanks again @Zebradil !
