### ISSUE TITLE
bug - url gets messed up with mobile navigation 

### ISSUE THREAD

**Issue by chad-bennett** [xianmin/hugo-theme-jane#64]
new to hugo and github commenting. apologies if writing too much or incorrectly. 

building a new blog using jane theme. lots of visual tweaking. can view working site [https://chad-bennett.github.io/home/](https://chad-bennett.github.io/home/)

when on mobile navigation, clicking a link in the sidebar adds to url instead of updating it. 
for example, when on **"categories/"** page and select "tags" link it goes to **"categories/tags/"** instead of **"tags/"**

only happens on mobile navigation. works completely fine on regular navigation.

**Comment by xianmin** [comment]
By the way, the color of your website looks great!
