### ISSUE TITLE
victor-hugo and jane

### ISSUE THREAD

**Issue by aborruso** [xianmin/hugo-theme-jane#68]
Hi,
first of all thank you for this beautiful theme.

I'm trying to develop a hugo website in netlify using victor-hugo boilerplate and Jane as theme.

When I work locally, I have no problem, when I open the build webiste in netlify, I have no `dist/jane.min.css` file in remote website.

Probably I must copy and paste some file from `victor-hugo/site/themes/hugo-theme-jane/src` to `victor-hugo/src`, but I do not know wich. Could you give me some help?

Thank you

**Comment by xianmin** [comment]
I am not familiar with `victor-hugo`. It looks a good boilerplate. If I have time, I will take a look.

For Jane-Theme project, there is a named `webpack.config.js` file in the root folder. This file has many config, and it is an important develop file.
