### ISSUE TITLE
RSS errors

### ISSUE THREAD

**Issue by aborruso** [xianmin/hugo-theme-jane#69]
Hi,
I have two errors when I run hugo:

- I have index.xml as output in my public folder, but if I open http://localhost:1313/index.xml, I have `404 page not found` (I do not have the 404 jane page);
- the RSS icon is associated to a wrong URL

![immagine](https://user-images.githubusercontent.com/30607/41766212-a8dacb9a-7606-11e8-8f05-ba4704e9dd1d.png)

How to solve these? 

I'm using `Hugo Static Site Generator v0.42.1 linux/amd64`.

Thank you very much

**Comment by aborruso** [comment]
I have this problem because I have uncommented this in config

```
[outputs]
  home = ["html", "jsonfeed"]
  page = ["html"]

[outputFormats]
[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true
```

I have changed it to and now it works

```
[outputs]
  home = ["html", "jsonfeed","rss"]
  page = ["html"]

[outputFormats]
[outputFormats.jsonfeed]
  mediaType = "application/json"
  baseName = "feed"
  isPlainText = true
```

**Comment by xianmin** [comment]
Thanks for your feedback and Pull requests! :smile:
