### ISSUE TITLE
How to add new menu like Project

### ISSUE THREAD

**Issue by yiyiwii** [xianmin/hugo-theme-jane#72]
This theme is really beautiful. I love it. But I got some problems.

I'd like to add a Project page:
```
[[menu.main]]
  name = "Projects"
  weight = 20
  identifier = "projects"
  url = "/projects/"
```

Also, I create a new folder called `projects` in `content`. And put some markdown files in `projects`.
When I click 'projects' (http://localhost:1313/projects/) in the navigation bar, the page is empty. 

Any suggestion? I guess I need to learn more about Hugo.

**Comment by xianmin** [comment]
The easy way:
1. Put all your posts in the `content/post` folder.
2. Set **category** or **tag** in your `project` posts.
3. set menu `url = "/tags/projects/"`

If you want enable **create a new folder called projects in content** , maybe this issue https://github.com/xianmin/hugo-theme-jane/issues/60 could help you.
