### ISSUE TITLE
Something strange about taxonomies

### ISSUE THREAD

**Issue by zstcode** [xianmin/hugo-theme-jane#73]
Hello, I'm new to hugo. I really love this theme. However, when I am deploying my blog with this theme, I found something strange about taxonomies.   

If I use this command ``hugo new about.md``, this will setup about.md at **``PathtoMyBlog\content\about.md``** . Then I add a ``categories: ["aboutme"]`` label to this markdown file. When running ``hugo server -D``, the categories of the site it generates seems to have a strange behavior.   
That is, If I open ``http://localhost:1313/categories/`` , it does **show the category "about" and ``http://localhost:1313/about/``** at this page. But however, when I open ``http://localhost:1313/categories/aboutme/``, it shows **nothing** and it does not show 404 page. 

So it is really different between these 2 pages. I know it is strange to set a category label for an about-me page but I am curious about which page shows the right thing. 

BTW, I want to set this lable because I find that when I use cell phone, the drop-down menu at the top of the page will **lose its children menu**. So I want to add it into a taxonomy page but will not be shown in the category of tag pages. I have tried to add a custom taxonomy ``hidecategories`` that will not be shown at the top menu just like what the document of hugo says, but at this ``http://localhost:1313/hidecategories/`` page, nothing will be shown. Could you tell me a way to deal with this problem? Maybe I should modify the code in ``taxonomy.html``?

**Comment by xianmin** [comment]
You are right! There is something strange about taxonomies.

1. `http://localhost:1313/categories/` will show all `category label` through all markdown files in the `/content/` folder, include any sub-folder files. The source code in `/layouts/_default/terms.html`.
2. `http://localhost:1313/categories/aboutme/` only show post item in the **`/content/post/`** folder and which category is `aboutme`. The source code in `/layouts/_default/taxonomy.html`.

This is a problem in the design of this theme. I will consider this particular question.
But very sorry, through your description, I still don't understand what your true intentions are.

If you want show `children menu` or `sub menu` in cell phone, this should be an enhancement for this theme.
If you want add a particular section page, like `http://localhost:1313/hidecategories/`, maybe this issue #60 could help you.

**Comment by zstcode** [comment]
Aha, very thanks to your reply! I just want to add a section page to bypass this problem that it shows differently in 2 pages. Anyway, I will check the isssue #60 and set my section page until the problem solved or the enhancement made in the future. Thanks for your help.
