### ISSUE TITLE
优酷的shortcode代码建议修改

### ISSUE THREAD

**Issue by lartpang** [xianmin/hugo-theme-jane#87]
https://github.com/xianmin/hugo-theme-jane/blob/46bbb7e0682844ee0ce5abeac9bcdaf5da29ebf7/layouts/shortcodes/youku.html#L3

此处

```
{{ .Get " id " }}?{{ with .Get "autoplay" }}{{ if eq . "true " }}
```
`id`&`true`处的空格感觉去掉比较好，一般的书写我觉得应该是这样的。

```
{{< youku id="_XMzcxODQ2NjM2NA==" autoplay="true" >}}
```

而且那个使用的优酷播放地址，

https://github.com/xianmin/hugo-theme-jane/blob/46bbb7e0682844ee0ce5abeac9bcdaf5da29ebf7/layouts/shortcodes/youku.html#L3

不如直接使用这个player的地址

https://github.com/xianmin/hugo-theme-jane/blob/46bbb7e0682844ee0ce5abeac9bcdaf5da29ebf7/layouts/shortcodes/youku.html#L9

来的有效

**Comment by xianmin** [comment]
感谢反馈！欢迎 PR！ :smile:
