### ISSUE TITLE
Consider adding rel="me" to social media links

### ISSUE THREAD

**Issue by jackbaty** [xianmin/hugo-theme-jane#9]
Another Indieweb request...

Add `rel="me"` to social media links so that they can be used for web sign-in. See https://indieweb.org/rel-me

I don't know if there's any harm in doing this automatically or if it should be configurable.

**Comment by xianmin** [comment]
https://indieweb.org/How_to_set_up_web_sign-in_on_your_own_domain

![deepinscreenshot_select-area_20180316233425](https://user-images.githubusercontent.com/2177570/37529622-9b078c32-2972-11e8-9f4e-ca83b304ba40.png)

Maybe `rel="me"` is not necessary.

**Comment by jackbaty** [comment]
Right, the services listed do add rel="me" to the links to your site in their profile pages but I believe you _also_ need rel="me" in the link _to_ their services from your site. In the meantime I'm just putting `<link rel="me" href="https://twitter.com/jackbaty" />` in the head section (using the new custom_head #8 feature :) ).
