### ISSUE TITLE
 site config value "zh-cn" for defaultContentLanguage does not match any language definition

### ISSUE THREAD

**Issue by choicky** [xianmin/hugo-theme-jane#92]
When I config `defaultContentLanguage` with `zh-cn`, `hugo server` prints out ` site config value "zh-cn" for defaultContentLanguage does not match any language definition`.

`zh-cn.yaml` already in `i18n` folder.  [Demo](https://itlaws.cn)

**Comment by shaform** [comment]
You need to set `[languages.zh-cn] languageCode = "zh-cn"` in your `config.toml` if you use `defaultContentLanguage = 'zh-cn'`

**Comment by choicky** [comment]
`config.toml` 已经设置了：
```
defaultContentLanguage = "zh-cn"           # Default language to use
[languages.zh-cn]
  languageCode = "zh-cn"
```

但是，菜单为什么还是英文的呢？https://itlaws.cn

**Comment by xianmin** [comment]
```
[[menu.main]] 
  name = "主页"
  weight = 10
  identifier = "home"
  url = "/"
```

Change the `name`  value.

**Comment by codertesla** [comment]
遇到同样问题。

按照提示添加后，没有再报错。

这里是我修改后的配置代码，供大家参考。

defaultContentLanguage = "zh-cn"           # Default language to use

[languages.en]
  languageCode = "en"

# 中文语言支持
[languages.zh-cn]
  languageCode = "zh-cn"


> You need to set `[languages.zh-cn] languageCode = "zh-cn"` in your `config.toml` if you use `defaultContentLanguage = 'zh-cn'`
