### ISSUE TITLE
计划支持文章的阅读数和站点的访问量吗？

### ISSUE THREAD

**Issue by yangwenmai** [xianmin/hugo-theme-jane#95]

**Comment by xianmin** [comment]
这个功能我会在空闲的时候添加的。

**Comment by maiyang** [comment]
我已经确认可以使用，谢谢。

**Comment by xianmin** [comment]
添加了「leancloud」 计数器。
使用方法可以参考： https://blog.csdn.net/u013553529/article/details/63357382

**Comment by midFang** [comment]
这是我的配置：
```
  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = true

  [params.counter.leancloud]
    enable = true
    app_id = "xxx"
    app_key = "xxx"
```

在文章中为什么是这样显示的，首页和文章详情页面多了阅读两个字
![](https://raw.githubusercontent.com/checkFang/img/master/20210506111539.png)

![](https://raw.githubusercontent.com/checkFang/img/master/20210506111613.png)

我的博客链接： midfang.com
