### ISSUE TITLE
请问已有 jane 主题的博客怎么升级？

### ISSUE THREAD

**Issue by yangwenmai** [xianmin/hugo-theme-jane#96]

**Comment by jostyee** [comment]
更新主题，然后hugo重新生成。。

**Comment by yangwenmai** [comment]
进入到 `theme/jane` ，然后执行 `git pull origin master`;
然后执行 `hugo server` ，就可以了吗？

更新的内容会在 `public` 里面，也就是 `hugo server` 时生成，对吧？

**Comment by shaform** [comment]
如果要更新 `public` 要用 `hugo` 指令 `hugo server` 不會變動 `public` 的內容

**Comment by choicky** [comment]
1、建议先 fork 一份，方便自己微调，且能够同步跟进官方的版本

2、建议通过 submodule 的方式下载 jane 主题

详见我的博文 [使用hugo搭建博客网站](https://itlaws.cn/post/hugo-guide/)

**Comment by lartpang** [comment]
对于fork后项目的更新可见 [github上fork了别人的项目后，再同步更新别人的提交](https://blog.csdn.net/qq1332479771/article/details/56087333)

综合上述各位的建议，可以用考虑如下步骤来更新：

1. 希望对该项目有后续的帮助支持
 * fork
 * git clone (choicky朋友提到使用submodule方式，也可以参考[git submodule](https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97) 你自己的`jane` 到 主题目录里
 * 有个性化定制可以考虑单独开一个分支存放，我是直接使用的原版本的
 * 可以利用PR的方式来更新自己的仓库分支
 * 再更新本地，可以使用如下代码，这里用的是fetch操作，而非pull操作，有些不同，参考
```
git fetch origin master
git log -p master..origin/master
git merge origin/master
```
 * 到你的hugo站点根目录，就是publish、content一级使用`hugo`指令重新生成public文件夹内容，可以使用`hugo server`查看效果
 * 后续没啥区别
 * 自己对主题进行改进，希望提出PR，可以先尝试提issue，再考虑提PR。

2. 只是直接使用
 直接对原始仓库进行`clone`操作，以及更新用的
```
git fetch origin master
git log -p master..origin/master
git merge origin/master
```

希望说了这么多，对你有用 @yangwenmai
